openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Contacts API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Contacts
  description: A contact defines the customer who holds an account or who is otherwise a person to contact about an account. An account requires a contact for the `BillToId` and `SoldToId` fields before the account can be active.
paths:
  /v1/contacts/{contactId}/scrub:
    put:
      summary: Scrub a contact
      operationId: PUT_ScrubContact
      description: 'Scrubs the sensitive data of a specific contact.


        You can use this operation to replace all sensitive data in a contact and its related contact snapshot with dummy values that will be stored in Zuora databases.


        After scrubbing a contact, it is good practice to delete it. Otherwise, it might cause errors in subsequent operations.


        **Note**: To use this operation, you must ensure that the "Scrub Sensitive Data of Contact" billing permission is enabled in your user role. Contact your tenant administrator if you want to enable this permission. See Scrub Contacts for more information.'
      tags:
      - Contacts
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: contactId
        in: path
        description: 'The ID of the contact that you want to scrub sensitive data from.

          '
        required: true
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponseType'
              example:
                success: true
  /v1/contacts:
    post:
      summary: Create a contact
      operationId: POST_CreateContact
      description: Creates a contact for a specified account.
      tags:
      - Contacts
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactResponse'
              example:
                accountId: 6e767220676e6e61206776652075207570
                accountNumber: A00000001
                address1: 314, Bongora
                address2: near Tech City
                city: GHY
                country: India
                county: null
                fax: '6174'
                firstName: Kuhi
                homePhone: '1234123'
                id: 6b65657020726f6c6c696e672021
                lastName: Das
                mobilePhone: '123213'
                nickname: Dorimi
                otherPhone: '2314213'
                otherPhoneType: Work
                personalEmail: kuhiroll@example.com
                state: Assam
                taxRegion: null
                workEmail: null
                workPhone: null
                zipCode: '123456'
                contactDescription: This is a description for the contact
                success: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTContactType'
        required: true
  /v1/contacts/{contactId}:
    get:
      summary: Retrieve a contact
      operationId: GET_Contact
      description: Retrieves detailed information about a specific contact.
      tags:
      - Contacts
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: contactId
        in: path
        description: 'The ID of the contact that you want to retrieve.

          '
        required: true
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactResponse'
              example:
                accountId: 72756e2061726e642026206465736572742075
                accountNumber: A00000001
                address1: 567, Rose Apartment
                address2: Gate no. 2
                city: Seattle
                country: United States
                county: King County
                fax: '123456'
                firstName: peter
                homePhone: '86123456789'
                id: 402881a2889f2e4301889f30e64e0019
                lastName: parker
                mobilePhone: '1234567890'
                nickname: peet
                otherPhone: '11111111111111111'
                otherPhoneType: Work
                personalEmail: peet@example.com
                state: Washington
                taxRegion: CA
                workEmail: work.mail@example.com
                workPhone: '3432'
                zipCode: '123134'
                contactDescription: This is a description
                success: true
    put:
      summary: Update a contact
      operationId: PUT_Contact
      description: 'Updates a contact for a specified account.


        You can update contacts for cancelled accounts.'
      tags:
      - Contacts
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: contactId
        in: path
        description: 'The ID of the contact that you want to update.

          '
        required: true
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactResponse'
              example:
                accountId: 6e767220676e6e61206d616b65207520637279
                accountNumber: A00000001
                address1: new Address
                address2: near Tech City
                city: Mumbai
                country: India
                county: null
                fax: '6174'
                firstName: Kuhi
                homePhone: '1234123'
                id: 8a90f50888a3036e0188ab7b3ffe7b8a
                lastName: Das
                mobilePhone: '123213'
                nickname: Dorimi
                otherPhone: '2314213'
                otherPhoneType: Work
                personalEmail: kuhiroll@example.com
                state: Assam
                taxRegion: null
                workEmail: null
                workPhone: null
                zipCode: '123134'
                contactDescription: This is the new Description
                success: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PUTContactType'
        required: true
    delete:
      summary: Delete a contact
      operationId: DELETE_Contact
      description: Deletes a contact.
      tags:
      - Contacts
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: contactId
        in: path
        description: 'The ID of the contact that you want to delete.

          '
        required: true
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponseType'
              example:
                success: true
components:
  parameters:
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Authorization_OAuth_optional:
      name: Authorization
      in: header
      required: false
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
  schemas:
    PUTContactType:
      allOf:
      - properties:
          address1:
            description: 'The first line of the contact''s address, which is often a street address or business name.

              '
            maxLength: 255
            type: string
          address2:
            description: 'The second line of the contact''s address.

              '
            maxLength: 255
            type: string
          city:
            description: 'The city of the contact''s address.

              '
            maxLength: 40
            type: string
          contactDescription:
            description: 'A description for the contact.

              '
            maxLength: 100
            type: string
          country:
            description: 'The country of the contact''s address.

              '
            maxLength: 64
            type: string
          county:
            description: 'The county. May optionally be used by Zuora Tax to calculate county tax.

              '
            maxLength: 32
            type: string
          fax:
            description: 'The contact''s fax number.

              '
            maxLength: 40
            type: string
          firstName:
            description: 'The contact''s first name.

              '
            maxLength: 100
            type: string
          homePhone:
            description: 'The contact''s home phone number.

              '
            maxLength: 40
            type: string
          lastName:
            description: 'The contact''s last name.

              '
            maxLength: 100
            type: string
          mobilePhone:
            description: 'The mobile phone number of the contact.

              '
            maxLength: 100
            type: string
          nickname:
            description: 'A nickname for the contact.

              '
            maxLength: 100
            type: string
          otherPhone:
            description: 'An additional phone number for the contact.

              '
            maxLength: 40
            type: string
          otherPhoneType:
            description: 'The type of the additional phone number.

              '
            enum:
            - Work
            - Mobile
            - Home
            - Other
            type: string
          personalEmail:
            description: 'The contact''s personal email address.

              '
            maxLength: 74
            type: string
          state:
            description: 'The state or province of the contact''s address.

              '
            maxLength: 40
            type: string
          taxRegion:
            description: 'If using Zuora Tax, a region string as optionally defined in your tax rules. Not required.

              '
            maxLength: 32
            type: string
          workEmail:
            description: 'The contact''s business email address.

              '
            maxLength: 74
            type: string
          workPhone:
            description: 'The contact''s business phone number.

              '
            maxLength: 40
            type: string
          zipCode:
            description: 'The zip code for the contact''s address.

              '
            maxLength: 20
            type: string
        type: object
      - $ref: '#/components/schemas/ContactObjectCustomFields'
      example:
        address1: new Address
        city: Mumbai
        contactDescription: This is the new Description
        mobilePhone: 123213
        zipCode: 123134
    ContactObjectCustomFields:
      additionalProperties:
        description: 'Custom fields of the Contact object. The name of each custom field has the form <code>*customField*__c</code>. Custom field names are case sensitive. See [Manage Custom Fields](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Manage_Custom_Fields) for more information.

          '
      description: 'Container for custom fields of a Contact object.

        '
      title: contactFieldsCustom
      type: object
    ContactResponse:
      allOf:
      - properties:
          accountId:
            description: 'The ID of the account associated with the contact.

              '
            type: string
          accountNumber:
            description: 'The number of the customer account associated with the contact.

              '
            type: string
          address1:
            description: 'The first line of the contact''s address, which is often a street address or business name.

              '
            maxLength: 255
            type: string
          address2:
            description: 'The second line of the contact''s address.

              '
            maxLength: 255
            type: string
          city:
            description: 'The city of the contact''s address.

              '
            maxLength: 40
            type: string
          contactDescription:
            description: 'A description for the contact.

              '
            maxLength: 100
            type: string
          country:
            description: 'The country of the contact''s address.

              '
            maxLength: 64
            type: string
          county:
            description: 'The county. May optionally be used by Zuora Tax to calculate county tax.

              '
            maxLength: 32
            type: string
          fax:
            description: "The contact's fax number. \n"
            maxLength: 40
            type: string
          firstName:
            description: 'The contact''s first name.

              '
            maxLength: 100
            type: string
          homePhone:
            description: 'The contact''s home phone number.

              '
            maxLength: 40
            type: string
          lastName:
            description: 'The contact''s last name.

              '
            maxLength: 100
            type: string
          mobilePhone:
            description: 'The mobile phone number of the contact.

              '
            maxLength: 100
            type: string
          nickname:
            description: 'A nickname for the contact.

              '
            maxLength: 100
            type: string
          otherPhone:
            description: 'An additional phone number for the contact.

              '
            maxLength: 40
            type: string
          otherPhoneType:
            description: 'The type of the additional phone number.

              '
            enum:
            - Work
            - Mobile
            - Home
            - Other
            type: string
          personalEmail:
            description: 'The contact''s personal email address.

              '
            maxLength: 74
            type: string
          state:
            description: 'The state or province of the contact''s address.

              '
            maxLength: 40
            type: string
          success:
            description: 'Returns `true` if the request was processed successfully.

              '
            type: boolean
          taxRegion:
            description: 'If using Zuora Tax, a region string as optionally defined in your tax rules. Not required.

              '
            maxLength: 32
            type: string
          workEmail:
            description: 'The contact''s business email address.

              '
            maxLength: 74
            type: string
          workPhone:
            description: 'The contact''s business phone number.

              '
            maxLength: 40
            type: string
          zipCode:
            description: 'The zip code for the contact''s address.

              '
            maxLength: 20
            type: string
        type: object
      - $ref: '#/components/schemas/ContactObjectCustomFields'
    CommonResponseType:
      properties:
        processId:
          description: 'The Id of the process that handle the operation.

            '
          type: string
        reasons:
          items:
            properties:
              code:
                description: 'The error code of response.

                  '
                type: string
              message:
                description: 'The detail information of the error response

                  '
                type: string
            type: object
          type: array
        success:
          description: 'Indicates whether the call succeeded.

            '
          type: boolean
      type: object
    POSTContactType:
      allOf:
      - properties:
          accountId:
            description: "The ID of the account associated with the contact. \n\n**Note**: When creating a contact, you must specify `accountNumber`, `accountId`, or both in the request body. If both fields are specified, they must correspond to the same account.\n"
            type: string
          accountNumber:
            description: "The number of the customer account associated with the contact. \n\n**Note**: When creating a contact, you must specify `accountNumber`, `accountId`, or both in the request body. If both fields are specified, they must correspond to the same account.\n"
            type: string
          address1:
            description: 'The first line of the contact''s address, which is often a street address or business name.

              '
            maxLength: 255
            type: string
          address2:
            description: 'The second line of the contact''s address.

              '
            maxLength: 255
            type: string
          city:
            description: 'The city of the contact''s address.

              '
            maxLength: 40
            type: string
          contactDescription:
            description: 'A description for the contact.

              '
            maxLength: 100
            type: string
          country:
            description: 'The country of the contact''s address.

              '
            maxLength: 64
            type: string
          county:
            description: 'The county. May optionally be used by Zuora Tax to calculate county tax.

              '
            maxLength: 32
            type: string
          fax:
            description: 'The contact''s fax number.

              '
            maxLength: 40
            type: string
          firstName:
            description: 'The contact''s first name.

              '
            maxLength: 100
            type: string
          homePhone:
            description: 'The contact''s home phone number.

              '
            maxLength: 40
            type: string
          lastName:
            description: 'The contact''s last name.

              '
            maxLength: 100
            type: string
          mobilePhone:
            description: 'The mobile phone number of the contact.

              '
            maxLength: 100
            type: string
          nickname:
            description: 'A nickname for the contact.

              '
            maxLength: 100
            type: string
          otherPhone:
            description: 'An additional phone number for the contact.

              '
            maxLength: 40
            type: string
          otherPhoneType:
            description: 'The type of the additional phone number.

              '
            enum:
            - Work
            - Mobile
            - Home
            - Other
            type: string
          personalEmail:
            description: 'The contact''s personal email address.

              '
            maxLength: 74
            type: string
          state:
            description: 'The state or province of the contact''s address.

              '
            maxLength: 40
            type: string
          taxRegion:
            description: 'If using Zuora Tax, a region string as optionally defined in your tax rules. Not required.

              '
            maxLength: 32
            type: string
          workEmail:
            description: 'The contact''s business email address.

              '
            maxLength: 74
            type: string
          workPhone:
            description: 'The contact''s business phone number.

              '
            maxLength: 40
            type: string
          zipCode:
            description: 'The zip code for the contact''s address.

              '
            maxLength: 20
            type: string
        required:
        - firstName
        - lastName
        type: object
      - $ref: '#/components/schemas/ContactObjectCustomFields'
      example:
        accountId: 6e767220676e6e61206776652075207570
        accountNumber: A00000001
        address1: 314, Bongora
        address2: near Tech City
        city: GHY
        contactDescription: This is a description for the contact
        country: India
        fax: '6174'
        firstName: Kuhi
        homePhone: '1234123'
        lastName: Das
        mobilePhone: '123213'
        nickname: Dorimi
        otherPhone: '2314213'
        otherPhoneType: Work
        personalEmail: kuhiroll@example.com
        state: Assam
        zipCode: '123456'
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
