openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Delivery Adjustments API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Delivery Adjustments
  description: Delivery Adjustments are used to handle end customer delivery complaints for the Delivery Pricing charge model. For more information, see Delivery Adjustments.
paths:
  /v1/adjustments:
    post:
      summary: Create a delivery adjustment
      operationId: Create_Adjustment
      description: 'Describes how to create one or more delivery adjustments for a subscription.


        **Notes**:

        - The Delivery Adjustments feature is in the Early Adopter phase. We are actively soliciting feedback from a small set of early adopters before releasing it as generally available. To manage and access this feature through the self-service interface, see Enable billing features by yourself in the Knowledge Center.

        - This operation supports a partial success scenario: when at least one eligible delivery adjustment exists for a given time period, “success = true” as well as eligible delivery adjustments and ineligible delivery adjustments are returned in the response; only when no delivery adjustment is eligible, “success=false” is returned.'
      tags:
      - Delivery Adjustments
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specify a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETAdjustmentsResponseType'
              example:
                totalNumberOfDeliveries: 1.0
                totalAmount: -5.0
                adjustments:
                - adjustmentId: 4028818886a2149b0186a237d0ff003b
                  adjustmentNumber: ADJ-00000001
                  deliveryDate: '2023-02-26'
                  deliveryDay: sunday
                  amount: -5.0
                  reason: string
                  subscriptionNumber: A-S00000001
                  chargeNumber: C-00000001
                  deferredRevenueAccountingCode: string
                  recognizedRevenueAccountingCode: string
                  revenueRecognitionRuleName: string
                  billingDate: '2023-02-26'
                  creditMemoNumber: CM00000001
                  status: Billed
                  eligible: true
                ineligibleAdjustments:
                - adjustmentId: null
                  adjustmentNumber: null
                  deliveryDate: '2023-02-27'
                  deliveryDay: monday
                  amount: null
                  reason: string
                  subscriptionNumber: A-S00000001
                  chargeNumber: C-00000001
                  deferredRevenueAccountingCode: string
                  recognizedRevenueAccountingCode: string
                  revenueRecognitionRuleName: string
                  billingDate: null
                  status: null
                  eligible: false
                  errorMessage: Subscription does not have a delivery scheduled for this day
                success: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTCreateBillingAdjustmentRequestType'
        required: true
    get:
      summary: List all delivery adjustments of a subscription
      operationId: GET_Subscription_Adjustments
      description: 'Describes how to retrieve detailed information about delivery adjustments of a subscription.


        **Note**: The Delivery Adjustments feature is in the Early Adopter phase. We are actively soliciting feedback from a small set of early adopters before releasing it as generally available. To manage and access this feature through the self-service interface, see Enable billing features by yourself in the Knowledge Center.'
      tags:
      - Delivery Adjustments
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: subscription-number
        in: query
        required: true
        description: 'A subscription number.

          '
        schema:
          type: string
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specify a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETAdjustmentsBySubscriptionNumberResponseType'
              example:
                adjustments:
                - adjustmentId: 4028818886a2149b0186a237d0ff003b
                  adjustmentNumber: ADJ-00000001
                  deliveryDate: '2023-02-26'
                  deliveryDay: sunday
                  amount: -5.0
                  reason: string
                  subscriptionNumber: A-S00000001
                  chargeNumber: C-00000001
                  deferredRevenueAccountingCode: string
                  recognizedRevenueAccountingCode: string
                  revenueRecognitionRuleName: string
                  billingDate: '2023-02-26'
                  creditMemoNumber: CM00000001
                  status: Billed
                - adjustmentId: 4028818886a2149b0186a2404f67003c
                  adjustmentNumber: ADJ-00000002
                  deliveryDate: '2023-02-27'
                  deliveryDay: monday
                  amount: -5.0
                  reason: string
                  subscriptionNumber: A-S00000001
                  chargeNumber: C-00000001
                  deferredRevenueAccountingCode: string
                  recognizedRevenueAccountingCode: string
                  revenueRecognitionRuleName: string
                  billingDate: '2023-02-27'
                  creditMemoNumber: CM00000002
                  debitMemoNumber: DM00000002
                  status: Cancelled
                success: true
  /v1/adjustments/{adjustment-key}:
    get:
      summary: Retrieve a delivery adjustment
      operationId: GET_Adjustment
      description: 'Describes how to retrieve detailed information about a delivery adjustment.


        **Note**: The Delivery Adjustments feature is in the Early Adopter phase. We are actively soliciting feedback from a small set of early adopters before releasing it as generally available. To manage and access this feature through the self-service interface, see Enable billing features by yourself in the Knowledge Center.'
      tags:
      - Delivery Adjustments
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: adjustment-key
        in: path
        description: The delivery adjustment ID or number to retrieve.
        required: true
        schema:
          type: string
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specify a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETAdjustmentByIdResponseType'
              example:
                adjustmentId: 4028818886a2149b0186a2404f67003c
                adjustmentNumber: ADJ-00000001
                deliveryDate: '2023-02-26'
                deliveryDay: sunday
                amount: -5.0
                reason: string
                subscriptionNumber: A-S00000001
                chargeNumber: C-00000001
                deferredRevenueAccountingCode: string
                recognizedRevenueAccountingCode: string
                revenueRecognitionRuleName: string
                billingDate: '2023-02-26'
                creditMemoNumber: CM00000001
                status: Billed
  /v1/adjustments/preview:
    post:
      summary: Preview a delivery adjustment
      operationId: Preview_Adjustment
      description: 'Describes how to preview delivery adjustments of a subscription.


        **Notes**:

        - The Delivery Adjustments feature is in the Early Adopter phase. We are actively soliciting feedback from a small set of early adopters before releasing it as generally available. To manage and access this feature through the self-service interface, see Enable billing features by yourself in the Knowledge Center.

        - This operation supports a partial success scenario: when at least one eligible delivery adjustment exists for a given time period, “success = true” as well as eligible delivery adjustments and ineligible delivery adjustments are returned in the response; only when no delivery adjustment is eligible, “success=false” is returned.'
      tags:
      - Delivery Adjustments
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specify a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETAdjustmentsResponseType'
              example:
                totalNumberOfDeliveries: 1.0
                totalAmount: -5.0
                adjustments:
                - adjustmentId: 'null'
                  adjustmentNumber: 'null'
                  deliveryDate: '2023-02-26'
                  deliveryDay: sunday
                  amount: -5.0
                  reason: string
                  subscriptionNumber: A-S00000001
                  chargeNumber: C-00000001
                  deferredRevenueAccountingCode: string
                  recognizedRevenueAccountingCode: string
                  revenueRecognitionRuleName: string
                  billingDate: '2023-02-26'
                  creditMemoNumber: null
                  status: null
                  eligible: true
                ineligibleAdjustments:
                - adjustmentId: null
                  adjustmentNumber: null
                  deliveryDate: '2023-02-27'
                  deliveryDay: monday
                  amount: null
                  reason: string
                  subscriptionNumber: A-S00000001
                  chargeNumber: C-00000001
                  deferredRevenueAccountingCode: string
                  recognizedRevenueAccountingCode: string
                  revenueRecognitionRuleName: string
                  billingDate: null
                  status: null
                  eligible: false
                  errorMessage: Subscription does not have a delivery scheduled for this day
                success: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTPreviewBillingAdjustmentRequestType'
        required: true
  /v1/adjustments/{adjustmentId}/cancel:
    put:
      summary: Cancel a delivery adjustment
      operationId: PUT_CancelAdjustment
      description: 'Describes how to cancel an unbilled delivery adjustment.


        **Note**: The Delivery Adjustments feature is in the Early Adopter phase. We are actively soliciting feedback from a small set of early adopters before releasing it as generally available. To manage and access this feature through the self-service interface, see Enable billing features by yourself in the Knowledge Center.'
      tags:
      - Delivery Adjustments
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: adjustmentId
        in: path
        description: 'The ID of the delivery adjustment to cancel.

          '
        required: true
        schema:
          type: string
          format: UUID
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specify a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETCancelAdjustmentResponseType'
              example:
                debitMemoNumber: DM00000001
                success: true
components:
  schemas:
    GETAdjustmentsResponseType:
      allOf:
      - $ref: '#/components/schemas/CommonResponseType'
      - properties:
          adjustments:
            description: 'Container for delivery adjustments of a subscription.

              '
            items:
              $ref: '#/components/schemas/POSTAdjustmentResponseType'
            type: array
          ineligibleAdjustments:
            description: 'Container for ineligible delivery adjustments of a subscription.

              '
            items:
              $ref: '#/components/schemas/POSTIneligibleAdjustmentResponseType'
            type: array
          totalAmount:
            description: 'The total amount of all the delivery adjustments.

              '
            format: number
            type: string
          totalNumberOfDeliveries:
            description: 'The total number of all delivery adjustments.

              '
            format: number
            type: string
        type: object
    POSTAdjustmentResponseType:
      allOf:
      - properties:
          adjustmentId:
            description: 'The system generated delivery adjustment ID.

              '
            format: UUID
            type: string
          adjustmentNumber:
            description: 'The system generated delivery adjustment number.

              '
            format: string
            type: string
          amount:
            description: 'The amount of the delivery adjustment.

              '
            format: number
            type: string
          billingDate:
            description: 'The billing date is same as the delivery date of the delivery adjustment, in `yyyy-mm-dd` format.

              '
            format: date
            type: string
          chargeNumber:
            description: 'The charge number in the subscription for which the delivery adjustment is created.

              '
            type: string
          creditMemoNumber:
            description: 'The Credit Memo generated for the delivery adjustment.

              '
            type: string
          deferredRevenueAccountingCode:
            description: 'The accounting code for the deferred revenue, such as Monthly Recurring Liability.

              '
            type: string
          deliveryDate:
            description: 'The delivery adjustment date, in `yyyy-mm-dd` format.

              '
            format: date
            type: string
          deliveryDay:
            description: 'The delivery adjustment day of the week.

              '
            format: string
            type: string
          eligible:
            description: 'The eligible flag is set as true for a successfully created delivery adjustment.

              '
            type: boolean
          reason:
            description: 'The reason for the delivery adjustment.

              '
            type: string
          recognizedRevenueAccountingCode:
            description: 'The accounting code for the recognized revenue, such as Monthly Recurring Charges or Overage Charges.

              '
            type: string
          revenueRecognitionRuleName:
            description: 'The name of the revenue recognition rule governing the revenue schedule.

              '
            type: string
          status:
            description: 'The status of the delivery adjustment will be `Billed` or `Cancelled`.

              '
            type: string
          subscriptionNumber:
            description: 'The subscription number for which the delivery adjustment is created.

              '
            type: string
        type: object
    POSTPreviewBillingAdjustmentRequestType:
      example:
        chargeNumbers:
        - string
        - string
        deferredRevenueAccountingCode: string
        endDate: '2023-02-27'
        exclusion:
        - chargeNumbers:
          - string
          - string
          deliveryDate: '2023-02-26'
        - chargeNumbers:
          - string
          - string
          deliveryDate: '2023-05-27'
        reason: string
        recognizedRevenueAccountingCode: string
        revenueRecognitionRuleName: string
        startDate: '2023-02-26'
        subscriptionNumber: string
        type: DeliveryCredit
      properties:
        accountNumber:
          description: "The account number for which the delivery adjustment is created.\n\n**Note**: \n  - The account number should be of the subscription owner.\n  - Only one of accountNumber or subscriptionNumber should be provided.\n"
          type: string
        chargeNumbers:
          description: 'An optional container to specify charge numbers in the subscription for which the delivery adjustment needs to be created.

            '
          items:
            type: string
          type: array
        deferredRevenueAccountingCode:
          description: 'The accounting code for the deferred revenue, such as Monthly Recurring Liability.

            '
          type: string
        endDate:
          description: 'The end date of the delivery adjustment, in `yyyy-mm-dd` format. This is inclusive.

            '
          format: date
          type: string
        reason:
          description: 'The reason for the delivery adjustment.

            '
          type: string
        recognizedRevenueAccountingCode:
          description: 'The accounting code for the recognized revenue, such as Monthly Recurring Charges or Overage Charges.

            '
          type: string
        revenueRecognitionRuleName:
          description: 'The name of the revenue recognition rule governing the revenue schedule.

            '
          type: string
        startDate:
          description: 'The start date of the delivery adjustment, in `yyyy-mm-dd` format. This is inclusive.

            '
          format: date
          type: string
        subscriptionNumber:
          description: 'The subscription number for which the delivery adjustment is created.


            **Note**: Only one of accountNumber or subscriptionNumber should be provided.

            '
          type: string
        type:
          description: 'The type of delivery adjustment.

            '
          enum:
          - DeliveryCredit
          type: string
      required:
      - startDate
      - endDate
      type: object
    POSTIneligibleAdjustmentResponseType:
      allOf:
      - properties:
          adjustmentId:
            description: 'The system generated delivery adjustment ID.

              '
            format: UUID
            type: string
          adjustmentNumber:
            description: 'The system generated delivery adjustment number.

              '
            format: string
            type: string
          amount:
            description: 'The amount of the delivery adjustment.

              '
            format: number
            type: string
          billingDate:
            description: 'The billing date of the delivery adjustment.

              '
            format: date
            type: string
          chargeNumber:
            description: 'The charge number in the subscription for which the delivery adjustment is created.

              '
            type: string
          deferredRevenueAccountingCode:
            description: 'The accounting code for the deferred revenue, such as Monthly Recurring Liability.

              '
            type: string
          deliveryDate:
            description: 'The delivery adjustment date, in `yyyy-mm-dd` format.

              '
            format: date
            type: string
          deliveryDay:
            description: 'The delivery adjustment day of the week.

              '
            format: string
            type: string
          eligible:
            description: 'The eligible flag is set as false for an unsuccessful delivery adjustment.

              '
            type: boolean
          errorMessage:
            description: "The reason due to which a delivery adjustment is not eligible on the given date. \n"
            type: string
          reason:
            description: 'The reason for the delivery adjustment.

              '
            type: string
          recognizedRevenueAccountingCode:
            description: 'The accounting code for the recognized revenue, such as Monthly Recurring Charges or Overage Charges.

              '
            type: string
          revenueRecognitionRuleName:
            description: 'The name of the revenue recognition rule governing the revenue schedule.

              '
            type: string
          status:
            description: 'The status of the delivery adjustment.

              '
            type: string
          subscriptionNumber:
            description: 'The subscription number for which the delivery adjustment is created.

              '
            type: string
        type: object
    POSTCreateBillingAdjustmentRequestType:
      example:
        chargeNumbers:
        - string
        - string
        deferredRevenueAccountingCode: string
        endDate: '2023-02-27'
        exclusion:
        - chargeNumbers:
          - string
          - string
          deliveryDate: '2023-02-26'
        - chargeNumbers:
          - string
          - string
          deliveryDate: '2023-05-27'
        reason: string
        recognizedRevenueAccountingCode: string
        revenueRecognitionRuleName: string
        startDate: '2023-02-26'
        subscriptionNumber: string
        type: DeliveryCredit
      properties:
        accountNumber:
          description: "The account number for which the delivery adjustment is created.  \n\n**Note**: \n  - The account number should be of the subscription owner.\n  - Only one of accountNumber or subscriptionNumber should be provided.\n"
          type: string
        chargeNumbers:
          description: 'An optional container to specify charge numbers in the subscription for which the delivery adjustment needs to be created.

            '
          items:
            type: string
          type: array
        deferredRevenueAccountingCode:
          description: 'The accounting code for the deferred revenue, such as Monthly Recurring Liability.

            '
          type: string
        endDate:
          description: 'The end date of the delivery adjustment, in `yyyy-mm-dd` format. This is inclusive.

            '
          format: date
          type: string
        exclusion:
          description: 'The charge numbers and the corresponding dates for exclusion of delivery adjustment.

            '
          items:
            properties:
              chargeNumbers:
                description: 'The charge numbers to be excluded from delivery adjustment on the specified delivery date.

                  '
                items:
                  type: string
                type: array
              deliveryDate:
                description: 'The date on which the delivery adjustment has to be excluded, in `yyyy-mm-dd` format.

                  '
                format: date
                type: string
            type: object
          type: array
        reason:
          description: 'The reason for the delivery adjustment.

            '
          type: string
        recognizedRevenueAccountingCode:
          description: 'The accounting code for the recognized revenue, such as Monthly Recurring Charges or Overage Charges.

            '
          type: string
        revenueRecognitionRuleName:
          description: 'The name of the revenue recognition rule governing the revenue schedule.

            '
          type: string
        startDate:
          description: 'The start date of the delivery adjustment, in `yyyy-mm-dd` format. This is inclusive.

            '
          format: date
          type: string
        subscriptionNumber:
          description: 'The subscription number for which the delivery adjustment is created.


            **Note**: Only one of accountNumber or subscriptionNumber should be provided.

            '
          type: string
        type:
          description: 'The type of delivery adjustment.

            '
          enum:
          - DeliveryCredit
          type: string
      required:
      - startDate
      - endDate
      type: object
    GETAdjustmentsBySubscriptionNumberResponseType:
      allOf:
      - $ref: '#/components/schemas/CommonResponseType'
      - properties:
          adjustments:
            description: 'Container for all the delivery adjustments of a subscription.

              '
            items:
              $ref: '#/components/schemas/GETAdjustmentByIdResponseType'
            type: array
        type: object
    CommonResponseType:
      properties:
        processId:
          description: 'The Id of the process that handle the operation.

            '
          type: string
        reasons:
          items:
            properties:
              code:
                description: 'The error code of response.

                  '
                type: string
              message:
                description: 'The detail information of the error response

                  '
                type: string
            type: object
          type: array
        success:
          description: 'Indicates whether the call succeeded.

            '
          type: boolean
      type: object
    GETAdjustmentByIdResponseType:
      allOf:
      - properties:
          adjustmentId:
            description: 'The system generated delivery adjustment ID.

              '
            format: UUID
            type: string
          adjustmentNumber:
            description: 'The system generated delivery adjustment Number.

              '
            format: string
            type: string
          amount:
            description: 'The amount of the delivery adjustment.

              '
            format: number
            type: string
          billingDate:
            description: 'The billing date is same as the delivery date of the delivery adjustment, in `yyyy-mm-dd` format.

              '
            format: date
            type: string
          chargeNumber:
            description: 'The charge number in the subscription for which the delivery adjustment is created.

              '
            type: string
          creditMemoNumber:
            description: 'The Credit Memo generated for the delivery adjustment.

              '
            type: string
          debitMemoNumber:
            description: "The Debit Memo generated to write off the Credit Memo for the delivery adjustment.    \n\n**Note**: This field is only visible when the delivery adjustment is in `Cancelled` status.\n"
            type: string
          deferredRevenueAccountingCode:
            description: 'The accounting code for the deferred revenue, such as Monthly Recurring Liability.

              '
            type: string
          deliveryDate:
            description: 'The delivery adjustment date, in `yyyy-mm-dd` format.

              '
            format: date
            type: string
          deliveryDay:
            description: 'The delivery adjustment day of the week.

              '
            format: string
            type: string
          reason:
            description: 'The reason for the delivery adjustment.

              '
            type: string
          recognizedRevenueAccountingCode:
            description: 'The accounting code for the recognized revenue, such as Monthly Recurring Charges or Overage Charges.

              '
            type: string
          revenueRecognitionRuleName:
            description: 'The name of the revenue recognition rule governing the revenue schedule.

              '
            type: string
          status:
            description: "The status of the delivery adjustment will be `Billed` or `Cancelled`.               \n"
            type: string
          subscriptionNumber:
            description: 'The subscription number for which the delivery adjustment is created.

              '
            type: string
        type: object
    GETCancelAdjustmentResponseType:
      allOf:
      - $ref: '#/components/schemas/CommonResponseType'
      - properties:
          debitMemoNumber:
            description: "The Debit Memo generated to write off the Credit Memo for the delivery adjustment.       \n"
            type: string
        type: object
  parameters:
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Authorization_OAuth_optional:
      name: Authorization
      in: header
      required: false
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
