openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Custom Payment Method Types API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Custom Payment Method Types
  description: Open Payment Method (OPM) service is a framework developed by Zuora, which allows you to integrate your custom payment method to Zuora subscription, billing, and revenue management in a dynamic and flexible manner.
paths:
  /open-payment-method-types:
    post:
      summary: Create a draft custom payment method type
      operationId: POST_CreateDraftOpenPaymentMethodType
      description: Creates a draft version of a custom payment method type. Revision number 1 is assigned to this version. You can update your draft version through the Update a custom payment method type operation. You must publish your draft version through the Publish a custom payment method type operation before your custom payment method type goes live.
      tags:
      - Custom Payment Method Types
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/POSTCreateOpenPaymentMethodTypeResponse'
              example:
                status: Draft
                paymentMethodType: AmazonPay__C_12368
                revision: 1
                publishDate: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTCreateOpenPaymentMethodTypeRequest'
        required: true
  /open-payment-method-types/publish/{paymentMethodTypeName}:
    put:
      summary: Publish a custom payment method type
      operationId: PUT_PublishOpenPaymentMethodType
      description: Publish the latest draft revision of a specific custom payment method type.
      tags:
      - Custom Payment Method Types
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - in: path
        name: paymentMethodTypeName
        required: true
        description: 'The API name of the custom payment method type, such as `AmazonPay__c_12368`.

          '
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PUTPublishOpenPaymentMethodTypeResponse'
              example:
                internalName: AmazonPay
                label: ZuoraQA Amazon Pay
                revision: 1
                version: '2021-11-22'
                status: Published
                tenantId: '9'
                entityId: ''
                methodReferenceIdField: AmazonToken
                userReferenceIdField: AmazonAccount
                subTypeField: AmazonTokenType
                fields:
                - name: AmazonToken
                  type: string
                  description: The Token value
                  defaultValue: null
                  label: AmazonToken
                  index: 1
                  maxLength: 100
                  minLength: 1
                  checksum: true
                  required: true
                  visible: true
                  representer: true
                  editable: true
                - name: AmazonTokenType
                  type: string
                  description: The Type of Token, e.g. GoCardlessToken
                  defaultValue: null
                  label: Amazon TokenType
                  index: 2
                  maxLength: 100
                  minLength: 1
                  checksum: true
                  required: true
                  visible: true
                  representer: true
                  editable: true
  /open-payment-method-types/{paymentMethodTypeName}:
    put:
      summary: Update a custom payment method type
      operationId: PUT_UpdateOpenPaymentMethodType
      description: 'Update the latest draft version of your custom payment method type. If the latest draft version has been published, the revision number is increased by 1 after the draft version is updated. You must publish your latest revision again through the Publish a custom payment method type operation before your updated custom payment method type goes live.


        **Note:** In the request body, you need to provide all the fields that define this custom payment method type including fields to be updated and the unchanged fields.'
      tags:
      - Custom Payment Method Types
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - in: path
        name: paymentMethodTypeName
        required: true
        description: 'The API name of the custom payment method type, such as `AmazonPay__c_12368`.

          '
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PUTUpdateOpenPaymentMethodTypeResponse'
              example:
                status: Draft
                paymentMethodType: AmazonPay__c_12368
                revision: 2
                publishDate: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PUTUpdateOpenPaymentMethodTypeRequest'
        required: true
  /open-payment-method-types/{paymentMethodTypeName}/draft/{revisionNumber}:
    get:
      summary: Retrieve a specific draft revision of a custom payment method type
      operationId: GET_OpenPaymentMethodTypeRevision
      description: Retrieves a specific draft revision of a custom payment method type.
      tags:
      - Custom Payment Method Types
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: paymentMethodTypeName
        in: path
        required: true
        description: 'The API name of the custom payment method type, such as `AmazonPay__c_12368`.

          '
        schema:
          type: string
      - name: revisionNumber
        in: path
        required: true
        description: 'The revision number of the draft revision to be retrieved.

          '
        schema:
          type: integer
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETOpenPaymentMethodTypeRevisionResponse'
              example:
                internalName: AmazonPay
                label: ZuoraQA Amazon Pay
                revision: 1
                version: '2021-11-22'
                status: Published
                tenantId: '9'
                entityId: f707d981-3ad2-4484-9c24-a93bf6b83411
                methodReferenceIdField: AmazonToken
                userReferenceIdField: AmazonAccount
                subTypeField: AmazonTokenType
                fields:
                - name: AmazonToken
                  type: string
                  description: The Token value
                  defaultValue: null
                  label: AmazonToken
                  index: 1
                  maxLength: 100
                  minLength: 1
                  checksum: true
                  required: true
                  visible: true
                  representer: true
                  editable: true
                - name: AmazonTokenType
                  type: string
                  description: The Type of Token, e.g. GoCardlessToken
                  defaultValue: null
                  label: Amazon TokenType
                  index: 2
                  maxLength: 100
                  minLength: 1
                  checksum: true
                  required: true
                  visible: true
                  representer: true
                  editable: true
  /open-payment-method-types/{paymentMethodTypeName}/published:
    get:
      summary: Retrieve a published custom payment method type
      operationId: GET_OpenPaymentMethodTypePublish
      description: Retrieves a published custom payment method type.
      tags:
      - Custom Payment Method Types
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: paymentMethodTypeName
        in: path
        required: true
        description: 'The API name of the custom payment method type, such as `AmazonPay__c_12368`.

          '
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETOpenPaymentMethodTypeRevisionResponse'
              example:
                internalName: AmazonPay
                label: ZuoraQA Amazon Pay
                revision: 1
                version: '2021-11-22'
                status: Published
                tenantId: '9'
                entityId: f707d981-3ad2-4484-9c24-a93bf6b83411
                methodReferenceIdField: AmazonToken
                userReferenceIdField: AmazonAccount
                subTypeField: AmazonTokenType
                fields:
                - name: AmazonToken
                  type: string
                  description: The Token value
                  defaultValue: null
                  label: AmazonToken
                  index: 1
                  maxLength: 100
                  minLength: 1
                  checksum: true
                  required: true
                  visible: true
                  representer: true
                  editable: true
                - name: AmazonTokenType
                  type: string
                  description: The Type of Token, e.g. GoCardlessToken
                  defaultValue: null
                  label: Amazon TokenType
                  index: 2
                  maxLength: 100
                  minLength: 1
                  checksum: true
                  required: true
                  visible: true
                  representer: true
                  editable: true
components:
  schemas:
    GETOpenPaymentMethodTypeRevisionResponse:
      properties:
        entityId:
          description: 'If an entity UUID is provided, this custom payment method type is specific to this entity only. If no entity UUID is provided, the custom payment method type is available to the global entity and all the sub entities in the tenant.

            '
          type: string
        fields:
          description: 'An array containing field metadata of the custom payment method type.

            '
          items:
            $ref: '#/components/schemas/OpenPaymentMethodTypeResponseFields'
          type: array
        internalName:
          description: 'A string to identify the custom payment method type in the API name of the payment method type.


            This field is used along with the `tenantId` field by the system to construct and generate the API name of the custom payment method type in the following way:


            `<internalName>__c_<tenantId>`


            For example, if `internalName` is `AmazonPay`, and `tenantId` is `12368`, the API name of the custom payment method type will be `AmazonPay__c_12368`.

            '
          type: string
        label:
          description: 'The label that is used to refer to this type in the Zuora UI.

            '
          type: string
        methodReferenceIdField:
          description: 'The identification reference of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.

            '
          type: string
        revision:
          description: 'The revision number of the custom payment method type, which starts from 1 and increases by 1 when you update a published revision for the first time.

            '
          type: integer
        status:
          description: 'The status of the custom payment method type.

            '
          type: string
        subTypeField:
          description: 'The identification reference indicating the subtype of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.

            '
          type: string
        tenantId:
          description: 'Zuora tenant ID. If multi-entity is enabled in your tenant, this is the ID of the parent tenant of all the sub entities.

            '
          type: string
        userReferenceIdField:
          description: 'The identification reference of the user or customer account.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.

            '
          type: string
        version:
          description: 'The time when the custom payment method type was first published.

            '
          type: string
    POSTCreateOpenPaymentMethodTypeResponse:
      properties:
        paymentMethodType:
          description: 'The API name of the custom payment method type.

            '
          type: string
        publishDate:
          description: 'The date when the custom payment method type was published. It is empty if the custom payment method type has not been published yet.

            '
          type: string
        revision:
          description: 'The revision number of the custom payment method type, which starts from 1 and increases by 1 when you update a published revision for the first time.

            '
          type: integer
        status:
          description: 'The status of the custom payment method type.

            '
          type: string
    OpenPaymentMethodTypeResponseFields:
      properties:
        checksum:
          description: 'The checksum value of a payment method is used to identify if this payment method is the same as another one, or if this payment method is altered to another new payment method.


            For example, if you select the credit card number and expiration date as the checksum fields for the CreditCard payment method type, when you modified the expiration date, Zuora considers this payment method as a different payment method compared to the original one.

            '
          type: boolean
        defaultValue:
          description: 'The default value of the field.

            '
          type: string
        description:
          description: 'An explanation of this field.

            '
          type: string
        editable:
          description: 'Specify `true` if this field can be updated through PUT API or UI.


            Note: If `editable` is set to `false`, you can specify the value of this field in the UI and POST API when creating a payment method. However, after you created the payment method, you cannot edit this field through PUT API or UI.

            '
          type: boolean
        index:
          description: 'The order of the field in this type, starting from 1.

            '
          type: integer
        label:
          description: 'The label that is used to refer to this field in the Zuora UI.

            '
          type: string
        maxLength:
          description: 'A maximum length limitation of the field value.

            '
          type: integer
        minLength:
          description: 'A minimal length limitation of the field value.

            '
          type: integer
        name:
          description: 'The API name of this field. It must be uinique.

            '
          type: string
        representer:
          description: 'This flag determines whether this field will be used for identifying this payment method in the Zuora UI. The field will be shown in the Payment Method field in the UI.

            '
          type: boolean
        required:
          description: 'Specify whether this field is required.

            '
          type: boolean
        type:
          description: 'The type of this field.

            '
          enum:
          - string
          - date
          - datetime
          - number
          - boolean
          type: string
        visible:
          description: "Specify `true` if this field can be retrieved through GET API or UI for displaying payment method details.\n\nNotes: \n  - If `visible` is set to `false`, you can still specify the value of this field in the UI and POST API when creating the payment method.\n  - If `visible` is set to `false` and `editable` is set to `true`, this field is not accessible through GET API or UI for displaying details, but you can still see it and edit the value in the UI and PUT API when updating this payment method.\n"
          type: boolean
      title: fields
    OpenPaymentMethodTypeRequestFields:
      properties:
        checksum:
          description: "The checksum value of a payment method is used to identify if this payment method is the same as another one, or if this payment method is altered to another new payment method.\n\nSet this flag to `true` for the following scenarios:\n  - The field should be part of checksum calculation.\n  - The field is a critical differentiator for this type. \n    \nFor example, if you select the credit card number and expiration date as the checksum fields for the CreditCard payment method type, when you modified the expiration date, Zuora considers this payment method as a different payment method compared to the original one.\n\nThis field cannot be `null` or empty.\n\nThis field cannot be updated after the creation of the custom payment method type.\n"
          type: boolean
        defaultValue:
          description: 'The default value of the field. `null` is supported.


            If a required field is added after the custom payment method type is published, `defaultValue` is required.


            This field cannot be updated after the creation of the custom payment method type.

            '
          maxLength: 255
          type: string
        description:
          description: 'An explanation of this field. It can be an empty string.

            '
          maxLength: 70
          type: string
        editable:
          description: 'Specify `true` if this field can be updated through PUT API or UI.


            This field cannot be `null` or empty.


            Note: If `editable` is set to `false`, you can specify the value of this field in the UI and POST API when creating a payment method. However, after you created the payment method, you cannot edit this field through PUT API or UI.

            '
          type: boolean
        index:
          description: 'The order of the field in this type, starting from 1. It must be unique.


            This field cannot be `null` or empty.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: integer
        label:
          description: 'The label that is used to refer to this field in the Zuora UI.


            An alphanumeric string, excluding JSON preserved characters e.g.  * \ ’ ”


            This field cannot be `null` or empty or any reserved field name.

            '
          maxLength: 30
          type: string
        maxLength:
          description: 'A maximum length limitation of the field value. The specified value must be in the range of [1,8000]. `maxLength` must be greater than or equal to `minLength`.


            After the custom payment method type is created, you can only increase the value of `maxLength`. Decreasing the value is not supported.

            '
          type: integer
        minLength:
          description: "A minimal length limitation of the field value.\n    \n0 <= `minLength` <= `maxLength`\n\nThe value of this metadata does not determine whether the field is a required field. It only defines the minimal length of the field value.\n\nAfter the custom payment method type is created, you can only decrease the value of `minLength`. Increasing the value is not supported.\n"
          type: integer
        name:
          description: 'The API name of this field. It must be uinique.


            An alphanumeric string starting with a capital letter, excluding JSON preserved characters e.g.  * \ ’ ”


            Though this field must be defined with a string starting with a capital letter, use this string with the first letter in lowercase when you specify it in other API operations. For example, `AmazonPayToken` is the defined value for `name`. In the request of the "Create a payment method" API operation, use `amazonPayToken`.


            This field cannot be `null` or empty or any reserved field name.


            This field cannot be updated after the creation of the custom payment method type.

            '
          maxLength: 30
          type: string
        representer:
          description: "This flag determines whether this field will be used for identifying this payment method in the Zuora UI. The field will be shown in the Payment Method field in the UI.\n\nThis field cannot be `null` or empty.\n\nNotes:\n  - In one custom payment method type, set `representer` to `true` for at least one field .\n  - In one custom payment method type, you can set `representer` to `true` for multiple fields.\n"
          type: boolean
        required:
          description: 'Specify whether this field is required.


            This field cannot be `null` or empty.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: boolean
        type:
          description: 'The type of this field.


            For the `date` type, ISO_LOCAL_DATE format is supported, such as `2011-12-03`. The timezone is not expected for the `date` type. For example, `2011-12-03+01:00` will be rejected.


            For the `datetime` type, only ISO_OFFSET_DATE_TIME format is supported, such as `2011-12-03T10:15:30+01:00`. Timezone must be included. A string like `2011-12-03T10:15:30` or `2011-12-03T10:15:30+01:00[Europe/Paris]` will be rejected.


            If you need to define a `date` type with timezone or a `datetime` type without timezone, use the `string` type for now.


            This field cannot be `null` or empty.


            This field cannot be updated after the creation of the custom payment method type.

            '
          enum:
          - string
          - date
          - datetime
          - number
          - boolean
          type: string
        visible:
          description: "Specify `true` if this field can be retrieved through GET API or UI for displaying payment method details.\n\nThis field cannot be `null` or empty.\n\nNotes: \n  - If `visible` is set to `false`, you can still specify the value of this field in the UI and POST API when creating the payment method.\n  - If `visible` is set to `false` and `editable` is set to `true`, this field is not accessible through GET API or UI for displaying details, but you can still see it and edit the value in the UI and PUT API when updating this payment method.\n"
          type: boolean
      title: fields
    PUTPublishOpenPaymentMethodTypeResponse:
      properties:
        entityId:
          description: 'If an entity UUID is provided, this custom payment method type is specific to this entity only. If no entity UUID is provided, the custom payment method type is available to the global entity and all the sub entities in the tenant.

            '
          type: string
        fields:
          description: 'An array containing field metadata of the custom payment method type.

            '
          items:
            $ref: '#/components/schemas/OpenPaymentMethodTypeResponseFields'
          type: array
        internalName:
          description: 'A string to identify the custom payment method type in the API name of the payment method type.


            This field is used along with the `tenantId` field by the system to construct and generate the API name of the custom payment method type in the following way:


            `<internalName>__c_<tenantId>`


            For example, if `internalName` is `AmazonPay`, and `tenantId` is `12368`, the API name of the custom payment method type will be `AmazonPay__c_12368`.

            '
          type: string
        label:
          description: 'The label that is used to refer to this type in the Zuora UI.

            '
          type: string
        methodReferenceIdField:
          description: 'The identification reference of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Payment Method Data Source Exports and Data Query.

            '
          type: string
        revision:
          description: 'The revision number of the custom payment method type, which starts from 1 and increases by 1 when you update a published revision for the first time.

            '
          type: integer
        status:
          description: 'The status of the custom payment method type.

            '
          type: string
        subTypeField:
          description: 'The identification reference indicating the subtype of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.

            '
          type: string
        tenantId:
          description: 'Zuora tenant ID. If multi-entity is enabled in your tenant, this is the ID of the parent tenant of all the sub entities.

            '
          type: string
        userReferenceIdField:
          description: 'The identification reference of the user or customer account.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.

            '
          type: string
        version:
          description: 'The time when the custom payment method type was first published.

            '
          type: string
    PUTUpdateOpenPaymentMethodTypeRequest:
      example:
        entityId: ''
        fields:
        - checksum: true
          defaultValue: null
          description: The Token value
          editable: true
          index: 1
          label: AmazonToken
          maxLength: 100
          minLength: 1
          name: AmazonToken
          representer: true
          required: true
          type: string
          visible: true
        - checksum: true
          defaultValue: null
          description: The Type of Token, e.g. GoCardlessToken
          editable: true
          index: 2
          label: Amazon TokenType
          maxLength: 100
          minLength: 1
          name: AmazonTokenType
          representer: true
          required: true
          type: string
          visible: true
        internalName: AmazonPay
        label: ZuoraQA Amazon Pay
        methodReferenceIdField: AmazonToken
        subTypeField: AmazonTokenType
        tenantId: '9'
        userReferenceIdField: ''
      properties:
        entityId:
          description: 'If this custom payment method type is specific to one entity only, specify the entity ID in UUID format when creating the draft payment method type, such as `123e4567-e89b-12d3-a456-426614174000`.


            You can only update this field to be empty, indicating that this custom payment method type is available to the global entity and all the sub entities in the tenant.

            '
          type: string
        fields:
          description: "An array containing field metadata of the custom payment method type.\n\nNotes:\n  - All the following nested metadata fields must be provided in the request to define a field. \n  - At least one field must be defined in the fields array for a custom payment method type. \n  - Up to 20 fields can be defined in the fields array for a custom method type.\n"
          items:
            $ref: '#/components/schemas/OpenPaymentMethodTypeRequestFields'
          type: array
        internalName:
          description: 'A string to identify the custom payment method type in the API name of the payment method type.


            The value of this field must be the same as the value specified when creating the draft revision of this custom payment method type.


            This field cannot be updated after the creation of the custom payment method type.


            This field is used along with the `tenantId` field by the system to construct and generate the API name of the custom payment method type in the following way:


            `<internalName>__c_<tenantId>`


            For example, if `internalName` is `AmazonPay`, and `tenantId` is `12368`, the API name of the custom payment method type will be `AmazonPay__c_12368`.

            '
          maxLength: 19
          type: string
        label:
          description: "The label that is used to refer to this type in the Zuora UI.\n\nThis value must be alphanumeric, excluding JSON preserved characters such as  * \\ ’ ” \n"
          maxLength: 40
          type: string
        methodReferenceIdField:
          description: 'The identification reference of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Payment Method Data Source Exports and Data Query.


            The value of this field must be the same as the value specified when creating the draft revision of this custom payment method type.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
        subTypeField:
          description: 'The identification reference indicating the subtype of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
        tenantId:
          description: 'Zuora tenant ID. If multi-entity is enabled in your tenant, this is the ID of the parent tenant of all the sub entities.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
        userReferenceIdField:
          description: 'The identification reference of the user or customer account.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
      required:
      - internalName
      - tenantId
      - label
      - methodReferenceIdField
      - fields
    POSTCreateOpenPaymentMethodTypeRequest:
      example:
        entityId: ''
        fields:
        - checksum: true
          defaultValue: null
          description: The Token value
          editable: true
          index: 1
          label: AmazonToken
          maxLength: 100
          minLength: 1
          name: AmazonToken
          representer: true
          required: true
          type: string
          visible: true
        - checksum: true
          defaultValue: null
          description: The Type of Token, e.g. GoCardlessToken
          editable: true
          index: 2
          label: Amazon TokenType
          maxLength: 100
          minLength: 1
          name: AmazonTokenType
          representer: true
          required: true
          type: string
          visible: true
        internalName: AmazonPay
        label: ZuoraQA Amazon Pay
        methodReferenceIdField: AmazonToken
        subTypeField: AmazonTokenType
        tenantId: '9'
        userReferenceIdField: ''
      properties:
        entityId:
          description: 'If this custom payment method type is specific to one entity only, provide the entity ID in this field in UUID format, such as `123e4567-e89b-12d3-a456-426614174000`. If no entity UUID is provided, the custom payment method type is available to the global entity and all the sub entities in the tenant.


            You can get the entity ID through the [Multi-entity: List entities](/api-references/older-api/operation/GET_Entities/) API operation or the **Manage Entity Profile** administration setting in the UI. To convert the format of the entity ID to UUID, separate the entity ID string in five groups with hyphens, in the form `<8-characters>-<4-characters>-<4-characters>-<4-characters>-<12-characters>` for a total of 36 characters.


            Note: After the custom payment method type is created, you can only update this field to be empty.

            '
          type: string
        fields:
          description: "An array containing field metadata of the custom payment method type.\n\nNotes:\n  - All the following nested metadata must be provided in the request to define a field. \n  - At least one field must be defined in the fields array for a custom payment method type. \n  - Up to 20 fields can be defined in the fields array for a custom payment method type.\n"
          items:
            $ref: '#/components/schemas/OpenPaymentMethodTypeRequestFields'
          type: array
        internalName:
          description: 'A string to identify the custom payment method type in the API name of the payment method type.


            This field must be alphanumeric, starting with a capital letter, excluding JSON preserved characters such as  * \ ’ ”. Additionally, ''_'' or ''-'' is not allowed.


            This field must be unique in a tenant.


            This field is used along with the `tenantId` field by the system to construct and generate the API name of the custom payment method type in the following way:


            `<internalName>__c_<tenantId>`


            For example, if `internalName` is `AmazonPay`, and `tenantId` is `12368`, the API name of the custom payment method type will be `AmazonPay__c_12368`.


            This field cannot be updated after the creation of the custom payment method type.

            '
          maxLength: 19
          type: string
        label:
          description: "The label that is used to refer to this type in the Zuora UI.\n\nThis value must be alphanumeric, excluding JSON preserved characters such as  * \\ ’ ” \n"
          maxLength: 40
          type: string
        methodReferenceIdField:
          description: 'The identification reference of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Payment Method Data Source Exports and Data Query.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
        subTypeField:
          description: 'The identification reference indicating the subtype of the custom payment method.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
        tenantId:
          description: 'Zuora tenant ID. If multi-entity is enabled in your tenant, this is the ID of the parent tenant of all the sub entities.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
        userReferenceIdField:
          description: 'The identification reference of the user or customer account.


            This field should be mapped to a field name defined in the `fields` array for the purpose of being used as a filter in reporting tools such as Data Source Exports and Data Query.


            This field cannot be updated after the creation of the custom payment method type.

            '
          type: string
      required:
      - internalName
      - tenantId
      - label
      - methodReferenceIdField
      - fields
    PUTUpdateOpenPaymentMethodTypeResponse:
      properties:
        paymentMethodType:
          description: 'The API name of the custom payment method type.

            '
          type: string
        publishDate:
          description: 'The date when the custom payment method type was published. It is emptry if the custom payment method type has not been published yet.

            '
          type: string
        revision:
          description: 'The revision number of the custom payment method type, which starts from 1 and increases by 1 when you update a published revision for the first time.

            '
          type: integer
        status:
          description: 'The status of the custom payment method type.

            '
          type: string
  parameters:
    GLOBAL_HEADER_Authorization_OAuth:
      name: Authorization
      in: header
      required: true
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
