openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Data Queries API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Data Queries
  description: The Data Query feature enables you to perform SQL queries in your Zuora tenant. To learn how to get started with Data Query, see Overview of Data Query.
paths:
  /query/jobs:
    post:
      operationId: POST_DataQueryJob
      summary: Submit a data query
      description: Submits a data query to be performed by Zuora and creates a query job. You can use Retrieve a data query job to track the status of the query job and obtain the URL of the query results.
      tags:
      - Data Queries
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitDataQueryResponse'
              example:
                data:
                  id: 3a3e85c4-96e7-486b-ae02-827120104301
                  query: SELECT accountnumber, balance FROM Account WHERE Account.balance > 100
                  useIndexJoin: false
                  sourceData: LIVE
                  queryStatus: accepted
                  remainingRetries: 3
                  updatedOn: '2018-08-17T13:14:18.204Z'
                  createdBy: 514f3ea1-6716-4f44-b6e0-9a8f0cf44bd2
        '400':
          description: Bad Request
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataQueryErrorResponse'
              example:
                code: 400
                message: Unable to process JSON
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitDataQueryRequest'
        required: true
    get:
      operationId: GET_DataQueryJobs
      summary: List data query jobs
      description: 'Returns a list of data query jobs that have been created in your Zuora tenant. You can filter the list by status.


        If you are an administrator, you can retrieve all the query jobs in your tenant. Otherwise, you can only retrieve your own query jobs.'
      tags:
      - Data Queries
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: queryStatus
        in: query
        required: false
        description: 'Filters the list of query jobs by status.

          '
        schema:
          type: string
          enum:
          - accepted
          - in_progress
          - completed
          - failed
          - cancelled
      - name: pageSize
        in: query
        required: false
        description: 'The number of records returned per page in the response.

          '
        schema:
          type: integer
          default: 20
          maximum: 100
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDataQueryJobsResponse'
              example:
                data:
                - id: bf3b5640-ddd1-4b4f-9a81-906ec2b84a89
                  query: SELECT s.id FROM Subscription s JOIN RatePlan rp ON s.id = rp.subscriptionid WHERE rp.name = 'Premium Monthly'
                  useIndexJoin: false
                  sourceData: LIVE
                  queryStatus: in_progress
                  remainingRetries: 3
                  updatedOn: '2018-08-17T13:14:38.855Z'
                  createdBy: 514f3ea1-6716-4f44-b6e0-9a8f0cf44bd2
                - id: 3a3e85c4-96e7-486b-ae02-827120104301
                  query: SELECT accountnumber, balance FROM Account WHERE Account.balance > 100
                  useIndexJoin: false
                  sourceData: LIVE
                  queryStatus: completed
                  dataFile: https://example.s3.us-west-2.amazonaws.com/3a3e85c4-96e7-486b-ae02-827120104301_24921638725108715.json?X-Amz-Security-Token=...
                  outputRows: 24516
                  processingTime: 9212
                  remainingRetries: 3
                  updatedOn: '2018-08-17T13:14:19.17Z'
                  createdBy: 514f3ea1-6716-4f44-b6e0-9a8f0cf44bd2
  /query/jobs/{job-id}:
    get:
      operationId: GET_DataQueryJob
      summary: Retrieve a data query job
      description: 'Retrieves a data query job. You can use this operation to track the status of the query job and obtain the URL of the query results.


        If you are an administrator, you can retrieve every query job in your tenant.


        If you are a non-admin user and try to retrieve a query job that you are not the owner of, you will get a 403 response indicating that you are forbidden from viewing this job. As a non-admin user, you can only retrieve your own query job.'
      tags:
      - Data Queries
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: job-id
        in: path
        required: true
        description: 'Internal identifier of the query job.

          '
        schema:
          type: string
          format: uuid
          maxLength: 36
          minLength: 36
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDataQueryJobResponse'
              example:
                data:
                  id: 3a3e85c4-96e7-486b-ae02-827120104301
                  query: SELECT accountnumber, balance FROM Account WHERE Account.balance > 100
                  useIndexJoin: false
                  sourceData: LIVE
                  queryStatus: completed
                  dataFile: https://example.s3.us-west-2.amazonaws.com/3a3e85c4-96e7-486b-ae02-827120104301_24921638725108715.json?X-Amz-Security-Token=...
                  outputRows: 24516
                  processingTime: 9212
                  remainingRetries: 3
                  updatedOn: '2018-08-17T13:14:19.17Z'
                  createdBy: 514f3ea1-6716-4f44-b6e0-9a8f0cf44bd2
        '403':
          description: Forbidden
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataQueryErrorResponse'
              example:
                code: 1009
                message: Access denied for restricted job ea50af05-6163-47e1-bf9b-c8e10648d8a3
        '404':
          description: Not Found
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataQueryErrorResponse'
              example:
                code: 1001
                message: 'No such query: 1e8e8586-5366-4cdf-a01d-fae3b2cf8427'
    delete:
      operationId: DELETE_DataQueryJob
      summary: Cancel a data query job
      description: Cancels a data query job, which prevents Zuora from performing the query. This operation is only applicable if the status of the query job is `accepted` or `in_progress`.
      tags:
      - Data Queries
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: job-id
        in: path
        required: true
        description: 'Internal identifier of the query job.

          '
        schema:
          type: string
          format: uuid
          maxLength: 64
          minLength: 64
      responses:
        '200':
          description: OK
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteDataQueryJobResponse'
              example:
                data:
                  id: 3a3e85c4-96e7-486b-ae02-827120104301
                  query: SELECT accountnumber, balance FROM Account WHERE Account.balance > 100
                  useIndexJoin: false
                  sourceData: LIVE
                  queryStatus: cancelled
                  remainingRetries: 3
                  updatedOn: '2018-08-17T13:22:16.965Z'
                  createdBy: 514f3ea1-6716-4f44-b6e0-9a8f0cf44bd2
        '400':
          description: Bad Request
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataQueryErrorResponse'
              example:
                code: 1003
                message: Query job c20a8ff4-3960-4c85-b067-d5259035f523 is not in accepted or in_progress status
components:
  schemas:
    GetDataQueryJobsResponse:
      properties:
        data:
          description: 'List of data query jobs. The query jobs are listed in reverse order of creation.

            '
          items:
            $ref: '#/components/schemas/DataQueryJob'
          type: array
      type: object
    DataQueryJob:
      allOf:
      - $ref: '#/components/schemas/DataQueryJobCommon'
      - properties:
          dataFile:
            description: 'The URL of the query results. Only applicable if the value of the `queryStatus` field is `completed`.

              '
            format: URL
            type: string
          outputRows:
            description: 'The number of rows the query results. Only applicable if the value of the `queryStatus` field is `completed`.

              '
            type: integer
          processingTime:
            description: 'Processing time of the query job, in milliseconds. Only applicable if the value of the `queryStatus` field is `completed`.

              '
            type: integer
          queryStatus:
            description: 'Status of the query job.


              * `submitted` - query submitted to query service for processing

              * `accepted` - query accepted by the query service

              * `in_progress` - query executed by the query service

              * `completed` - query execution completed by the query service

              * `failed` - query unable to be processed by the query service

              * `cancelled` - query cancelled by the user


              If the value of this field is `completed`, the `dataFile` field contains the location of the query results.


              If the value of this field is `accepted` or `in_progress`, you can use [Cancel a data query job](#operation/DELETE_DataQueryJob) to prevent Zuora from performing the query. Zuora then sets the status of the query job to `cancelled`.

              '
            enum:
            - submitted
            - accepted
            - in_progress
            - completed
            - failed
            - cancelled
            type: string
        type: object
      description: 'A data query job.

        '
      title: queryJob
    DataQueryJobCancelled:
      allOf:
      - $ref: '#/components/schemas/DataQueryJobCommon'
      - properties:
          queryStatus:
            description: 'Status of the query job.

              '
            enum:
            - cancelled
            type: string
        type: object
      description: 'A cancelled data query job.

        '
      title: cancelledQueryJob
    DataQueryJobCommon:
      properties:
        createdBy:
          description: 'The query job creator''s Id.

            '
          format: uuid
          maxLength: 64
          minLength: 64
          type: string
        id:
          description: 'Internal identifier of the query job.

            '
          format: uuid
          maxLength: 64
          minLength: 64
          type: string
        query:
          description: 'The query that was submitted.

            '
          type: string
        remainingRetries:
          description: 'The number of times that Zuora will retry the query if Zuora is unable to perform the query.

            '
          type: integer
        sourceData:
          description: 'Indicates the source that data queries run against:


            * `LIVE` represents the live transactional databases at Zuora (Data Query Live).


            * `WAREHOUSE` represents Zuora Warehouse, which has better performance and fewer limitations than the live transactional database. For more information, see <a href="https://knowledgecenter.zuora.com/Zuora_Central_Platform/Zuora_Warehouse/A_Zuora_Warehouse_overview" target="_blank">Zuora Warehouse</a>.

            '
          type: string
        updatedOn:
          description: 'Date and time when the query job was last updated, in ISO 8601 format.

            '
          format: date-time
          type: string
        useIndexJoin:
          description: 'Indicates whether to use Index Join. See <a href="https://knowledgecenter.zuora.com/Zuora_Central_Platform/Query/Data_Query/Best_practices_when_writing_data_queries/General_best_practices#Index_JOIN" target="_blank">Index Join</a> for more information.

            '
          type: boolean
      type: object
    SubmitDataQueryRequest:
      example:
        compression: NONE
        output:
          target: S3
        outputFormat: JSON
        query: SELECT accountnumber, balance FROM Account WHERE Account.balance > 100
        sourceData: LIVE
      properties:
        columnSeparator:
          description: 'The column separator. Only applicable if the `outputFormat` is `DSV`.

            '
          type: string
        compression:
          description: 'Specifies whether Zuora compresses the query results.

            '
          enum:
          - NONE
          - GZIP
          - ZIP
          type: string
        encryptionKey:
          description: "Base-64 encoded public key of an RSA key-pair. \n\nNote that Data Query only supports 1024-bit RSA keys.\n\nIf you set this field, Zuora encrypts the query results using the provided public key. You must use the corresponding private key to decrypt the query results.\n"
          format: byte
          type: string
        output:
          description: 'Additional information about the query results.

            '
          properties:
            target:
              description: 'Set this field to `S3`.

                '
              enum:
              - S3
              type: string
          required:
          - target
          type: object
        outputFormat:
          description: 'Specifies the format of the query results.


            * `JSON` - Each row in the query results will be a JSON object. The format of the query result file is [JSON Lines](http://jsonlines.org/).

            * `CSV` - Each row in the query results will be a comma-separated list of values.

            * `TSV` - Each row in the query results will be a tab-separated list of values.

            * `DSV` - Pass any character as your custom delimiter into the `columnSeparator` field.

            '
          enum:
          - JSON
          - CSV
          - TSV
          - DSV
          type: string
        query:
          description: 'The query to perform. See [SQL Queries in Data Query](https://knowledgecenter.zuora.com/DC_Developers/BA_Data_Query/BA_SQL_Queries_in_Data_Query) for more information.

            '
          type: string
        readDeleted:
          default: false
          description: 'Indicates whether the query will retrieve only the deleted record. If `readDeleted` is set to `false` or it is not included in the request body, the query will retrieve only the non-deleted records. If it is set to `true`, only the deleted records will be retrieved.


            If you select the `deleted` column in the `query` field, both non-deleted and deleted records will be retrieved regardless of the value in the `readDeleted` field.


            Note that Data Query is subject to Zuora Data Retention Policy. The retention period of deleted data is 30 days. You can only retrieve deleted data for 30 days through Data Query.

            '
          type: boolean
        sourceData:
          description: 'Specify the source that data queries run against:


            * `LIVE` represents the live transactional databases at Zuora (Data Query Live).


            * `WAREHOUSE` represents Zuora Warehouse, which has better performance and fewer limitations than the live transactional database. This option is available only if you have the Zuora Warehouse feature enabled in your tenant. For more information, see <a href="https://knowledgecenter.zuora.com/Zuora_Central_Platform/Zuora_Warehouse/A_Zuora_Warehouse_overview" target="_blank">Zuora Warehouse</a>. <br>If this option is selected, you can specify warehouse size in `warehouseSize`.


            If this field is not specified, the default value `LIVE` will be used.

            '
          enum:
          - LIVE
          - WAREHOUSE
          type: string
        useIndexJoin:
          description: Indicates whether to use Index Join. Index join is useful when you have a specific reference value in your WHERE clause to index another large table by. See [Use Index Join](https://knowledgecenter.zuora.com/DC_Developers/BA_Data_Query/Best_practices_of_Data_Query#Use_Index_Join) for more information.
          type: boolean
        warehouseSize:
          description: 'Specify the size of Zuora Warehouse. This field is available only if the `sourceData` is `WAREHOUSE`.


            If this field is not specified or set to `NULL`, the default value `xsmall` will be used.

            '
          enum:
          - xsmall
          - 'NULL'
          type: string
      required:
      - query
      - outputFormat
      - compression
      - output
      type: object
    DeleteDataQueryJobResponse:
      properties:
        data:
          $ref: '#/components/schemas/DataQueryJobCancelled'
      type: object
    GetDataQueryJobResponse:
      properties:
        data:
          $ref: '#/components/schemas/DataQueryJob'
      type: object
    DataQueryErrorResponse:
      properties:
        code:
          description: 'Error code.

            '
          type: integer
        message:
          description: 'Error message.

            '
          type: string
      type: object
    SubmitDataQueryResponse:
      properties:
        data:
          $ref: '#/components/schemas/DataQueryJob'
      type: object
  parameters:
    GLOBAL_HEADER_Authorization_OAuth:
      name: Authorization
      in: header
      required: true
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
