openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Bill Run API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Bill Run
  description: 'Use the Bill Run call to create ad hoc bill runs and Post, Cancel, Query, and Delete bill runs.


    For more information about bill runs, see Bill runs.'
paths:
  /v1/bill-runs:
    post:
      summary: Create a bill run
      operationId: POST_CreateBillRun
      description: 'Creates an ad-hoc bill run or a scheduled bill run.

        - Support to create ad-hoc or scheduled bill runs by batch

        - Support to create ad-hoc or scheduled bill runs for a single account (all subscriptions under this account)

        - Support to create a bill run by subscription (50 or less subscriptions under the same account)


        To use this operation, you must have the Create Bill Runs billing permission.


        **Restrictions and limitations**


        When using this operation to create bill runs, keep the following restrictions and limitations in mind:

        - When creating batch-level bill runs, you must specify `batches` and cannot specify `billRunFilters`.

        - When creating account-level bill runs, you must specify `billRunFilters` and cannot specify `batches`. Only one single account is allowed.

        - When creating subscription-level bill runs, you must specify `billRunFilters` and cannot specify `batches`. All subscriptions must belong to the same account. At most 50 subscriptions are allowed.

        - If more than 500 bill runs created through this operation are in `Pending` status, you cannot use this operation to create any more bill runs.'
      tags:
      - Bill Run
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillRunResponseType'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTCreateBillRunRequestType'
        required: true
  /v1/bill-runs/{billRunId}/post:
    put:
      summary: Post a bill run
      operationId: PUT_PostBillRun
      description: 'Posts a bill run asynchronously. To post a bill run, the current bill run must be in `Completed` status.


        When a bill run is being posted, its status is changed to `PostInProgress`. After all invoices for this bill run are posted, its status is changed to `Posted`.'
      tags:
      - Bill Run
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: billRunId
        in: path
        required: true
        description: 'The unique ID of a bill run.

          '
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillRunResponseType'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                invoiceDate:
                  type: string
                  format: date
                  description: "The date that appears on the invoice being created, in `yyyy-mm-dd` format. \n\nThe value cannot fall in a closed accounting period.\n"
              required:
              - invoiceDate
              example:
                invoiceDate: '2022-01-01'
        required: true
  /v1/bill-runs/{billRunId}:
    get:
      summary: Retrieve a bill run
      operationId: GET_BillRun
      description: Retrieves the information about a specific bill run.
      tags:
      - Bill Run
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: billRunId
        in: path
        description: 'The unique ID of a bill run.

          '
        required: true
        schema:
          type: string
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillRunResponseType'
    delete:
      summary: Delete a bill run
      operationId: DELETE_DeleteBillRun
      description: Deletes a bill run. You can only delete bill runs in `Canceled` or `Error` status.
      tags:
      - Bill Run
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: billRunId
        in: path
        required: true
        description: 'The unique ID of a bill run.

          '
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBillRunResponseType'
  /v1/bill-runs/{billRunId}/cancel:
    put:
      summary: Cancel a bill run
      operationId: PUT_CancelBillRun
      description: 'Cancels a bill run in Draft status.


        When cancelling a scheduled bill run, keep the following information in mind:

        - If you set `cancelOnce` to `true`, only the current bill run is cancelled. The other future scheduled bill runs will be automatically executed based on the schedule.

        - If you set `cancelOnce` to `false`, all future recurring bill runs are cancelled.'
      tags:
      - Bill Run
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: billRunId
        in: path
        required: true
        description: 'The unique ID of a bill run.

          '
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelBillRunResponseType'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cancelOnce:
                  type: boolean
                  default: true
                  description: 'Whether to cancel the current bill run or cancel all future recurring bill runs, only valid for a scheduled bill run.

                    '
              example:
                cancelOnce: true
        required: true
  /v1/bill-runs/{billRunKey}/emails:
    post:
      summary: Email billing documents generated from a bill run
      operationId: POST_EmailBillingDocumentsfromBillRun
      description: 'Manually emails all the billing documents that are generated from a specified bill run to your customers.


        Bill runs can generate invoices and credit memos based on your invoice and credit memo generation rule. Credit memos are only available if you have the Invoice Settlement feature enabled.


        Using this API operation, the billing documents are sent to the email addresses specified in the **To Email** field of the email templates. The email template used for each billing document is set in the **Delivery Options** panel of the **Edit notification** dialog from the Zuora UI. See Edit Email Templates for more information about how to edit the **To Email** field in the email template.


        ### Notes

        - Even though no field is required in the Request body, you still need to specify `{}` in the request. Otherwise, an error will be returned.


        - You can only email posted billing documents.


        - You must activate the following notifications before emailing invoices and credit memos:

        - **Manual Email For Invoice | Manual Email For Invoice**

        - **Email Credit Memo | Manually email Credit Memo**


        - To include the invoice PDF in the email, select the **Include Invoice PDF** check box in the **Edit notification** dialog from the Zuora UI. To include the credit memo PDF in the email, select the **Include Credit Memo PDF** check box in the **Edit notification** dialog from the Zuora UI. See Create and Edit Notifications for more information.


        - Zuora sends the email messages based on the email template you set. You can set the email template to use in the **Delivery Options** panel of the **Edit notification** dialog from the Zuora UI. By default, the following templates are used for billing documents:

        - Invoices: **Invoice Posted Default Email Template**

        - Credit memos: **Manual Email for Credit Memo Default Template**


        See Create and Edit Email Templates for more information.'
      tags:
      - Bill Run
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponseType'
              example:
                success: true
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: billRunKey
        in: path
        required: true
        description: 'The ID or number of the bill run. For example, 2c92c8f95d0c886e015d11287a8f0f8b or BR-00000001.

          '
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTEmailBillingDocfromBillRunType'
        required: true
components:
  schemas:
    BillRunFilterRequestType:
      allOf:
      - properties:
          accountId:
            description: "The target account of the bill run. \n\nIf multiple subscriptions are specified, the account ID must be the same.\n"
            type: string
          filterType:
            description: 'To create bill runs at account level or subscription level.

              '
            enum:
            - Account
            - Subscription
            type: string
          subscriptionId:
            description: "The target subscripiton ID of the account. \n\nIf you set the `filterType` field to `Subscription`, you must specify the `subscriptionId` field.\n"
            type: string
        required:
        - accountId
        - filterType
        type: object
      title: billRunFilters
    NextRunResponseType:
      allOf:
      - description: 'Container about information about the next bill run to be executed.

          '
        properties:
          autoEmail:
            description: 'Whether to automatically send emails after Auto-Post is complete.

              '
            type: boolean
          autoPost:
            description: 'Whether to automatically post the bill run after the bill run is created.

              '
            type: boolean
          autoRenewal:
            description: 'Whether to automatically renew auto-renew subscriptions that are up for renewal.

              '
            type: boolean
          batches:
            description: "The batch of accounts for this bill run. \n\n**Values:** `AllBatches` or an array of `Batch`*n* where *n* is one of numbers 1 - 50, for example, `Batch7`.\n"
            items:
              type: string
            type: array
          billCycleDay:
            description: "The day of the bill cycle. This field is only valid if the `batches` field is specified.\n\n**Values:** \n- `AllBillCycleDays` or one of numbers 1 - 31 for an ad-hoc bill run\n- `AllBillCycleDays`, one of numbers 1 - 31, or `AsRunDay` for a scheduled bill run\n"
            type: string
          billRunFilters:
            description: "The target account or subscriptions for this bill run. \n"
            items:
              $ref: '#/components/schemas/BillRunFilterResponseType'
            type: array
          billRunNumber:
            description: 'The number of the bill run.

              '
            type: string
          chargeTypeToExclude:
            description: 'The types of the charges to be excluded from the generation of billing documents.

              '
            items:
              enum:
              - OneTime
              - Recurring
              - Usage
              type: string
            type: array
          createdById:
            description: 'The ID of the user who created the bill run.

              '
            type: string
          createdDate:
            description: 'The date and time when the bill run was created.

              '
            format: date-time
            type: string
          id:
            description: 'The ID of the bill run.

              '
            type: string
          invoiceDate:
            description: 'The invoice date for this bill run, only valid for ad-hoc bill runs.

              '
            format: date
            type: string
          invoiceDateOffset:
            description: 'The offset compared to the bill run execution date, only valid for scheduled bill runs.

              '
            type: integer
          noEmailForZeroAmountInvoice:
            description: "Whether to suppress emails for invoices with zero total amount generated in this bill run after the bill run is complete. \n"
            type: boolean
          schedule:
            $ref: '#/components/schemas/BillRunScheduleResponseType'
          scheduledExecutionTime:
            description: 'The scheduled execution time for the bill run.

              '
            format: date-time
            type: string
          status:
            description: 'The status of the bill run.

              '
            enum:
            - Pending
            - Processing
            - Completed
            - Error
            - Canceled
            - Posted
            - PostInProgress
            - CancelInProgress
            - RemoveInProgress
            - Paused
            type: string
          targetDate:
            description: 'The target date for this bill run, only valid for ad-hoc bill runs.

              '
            format: date
            type: string
          targetDateOffset:
            description: 'The offset compared to the bill run execution date, only valid for scheduled bill runs.

              '
            type: integer
          updatedById:
            description: 'The ID of the user who last updated the bill run.

              '
            type: string
          updatedDate:
            description: 'The date and time when the bill run was last updated.

              '
            format: date-time
            type: string
        type: object
      example:
        autoEmail: false
        autoPost: false
        autoRenewal: false
        batches: null
        billCycleDay: null
        billRunFilters:
        - accountId: 2c9081a03c63c94c013c66688a2c00bf
          filterType: Subscription
          subscriptionId: 402882297e387c51017e38a245c313db
        billRunNumber: BR-00000016
        chargeTypeToExclude:
        - OneTime
        - Usage
        createdById: ff808081298c6e5401298c7274a40005
        createdDate: '2022-01-24 19:58:27'
        id: 2c9890077e8a8490017e8bf3a5171a43
        invoiceDate: '2020-02-01'
        invoiceDateOffset: null
        noEmailForZeroAmountInvoice: false
        schedule: null
        scheduledExecutionTime: null
        status: Pending
        success: true
        targetDate: '2020-02-01'
        targetDateOffset: null
        updatedById: ff808081298c6e5401298c7274a40005
        updatedDate: '2022-01-24 19:58:27'
      title: nextRun
    POSTEmailBillingDocfromBillRunType:
      example:
        resend: 'true'
      properties:
        resend:
          default: false
          description: 'Whether to send out emails for all the billing documents that are associated with the bill run. If the value is `false`, emails are sent out only for the billing documents that never have emails sent out.

            '
          type: boolean
      type: object
    CancelBillRunResponseType:
      allOf:
      - $ref: '#/components/schemas/GetBillRunResponseType'
      - properties:
          nextRun:
            $ref: '#/components/schemas/NextRunResponseType'
        type: object
      example:
        autoEmail: false
        autoPost: false
        autoRenewal: true
        batches: null
        billCycleDay: null
        billRunFilters: []
        billRunNumber: BR-00000014
        chargeTypeToExclude: null
        createdById: ff808081298c6e5401298c7274a40005
        createdDate: '2022-01-19 11:28:34'
        id: 2c9890e97e57e546017e706109df04a1
        invoiceDate: '2022-01-26'
        invoiceDateOffset: 0
        name: test
        nextRun:
          autoEmail: false
          autoPost: false
          autoRenewal: true
          batches: null
          billCycleDay: null
          billRunFilters: []
          billRunNumber: BR-00000021
          chargeTypeToExclude: null
          createdById: ff808081298c6e5401298c7274a40005
          createdDate: '2022-01-26 14:47:05'
          id: 2c9890077e901749017e95235b13093d
          invoiceDate: null
          invoiceDateOffset: 0
          noEmailForZeroAmountInvoice: false
          schedule:
            repeatFrom: '2022-02-28'
            repeatTo: '2023-01-31'
            repeatType: Monthly
            runTime: 0
            weeklyOnDay: null
          scheduledExecutionTime: '2022-02-28 00:00:00'
          status: Pending
          targetDate: null
          targetDateOffset: 0
          updatedById: ff808081298c6e5401298c7274a40005
          updatedDate: '2022-01-26 14:47:05'
        noEmailForZeroAmountInvoice: false
        schedule: null
        scheduledExecutionTime: '2022-01-28 00:00:00'
        status: CancelInProgress
        success: true
        targetDate: null
        targetDateOffset: 0
        updatedById: ff808081298c6e5401298c7274a40005
        updatedDate: '2022-01-26 14:47:09'
    GetBillRunResponseType:
      allOf:
      - properties:
          autoEmail:
            description: 'Whether to automatically send emails after Auto-Post is complete.

              '
            type: boolean
          autoPost:
            description: 'Whether to automatically post the bill run after the bill run is created.

              '
            type: boolean
          autoRenewal:
            description: 'Whether to automatically renew auto-renew subscriptions that are up for renewal.

              '
            type: boolean
          batches:
            description: 'The batch of accounts for this bill run, this field can not exist with `billRunFilters` together.


              **Values:** `AllBatches` or an array of `Batch`*n* where *n* is a number between 1 and 50, for example, `Batch7`.

              '
            items:
              type: string
            type: array
          billCycleDay:
            description: "The day of the bill cycle, this field is only valid when `batches` is specified.\n\n**Values:** \n- `AllBillCycleDays` or one of numbers 1 - 31 for an ad-hoc bill run\n- `AllBillCycleDays`, one of numbers 1 - 31, or `AsRunDay` for a scheduled bill run\n"
            type: string
          billRunFilters:
            description: 'The target account or subscriptions for this bill run.

              '
            items:
              $ref: '#/components/schemas/BillRunFilterResponseType'
            type: array
          billRunNumber:
            description: 'The number of the bill run.

              '
            type: string
          chargeTypeToExclude:
            description: 'The types of the charges to be excluded from the generation of billing documents.

              '
            items:
              enum:
              - OneTime
              - Recurring
              - Usage
              type: string
            type: array
          createdById:
            description: 'The ID of the user who created the bill run.

              '
            type: string
          createdDate:
            description: 'The date and time when the bill run was created.

              '
            format: date-time
            type: string
          id:
            description: 'The unqie ID of the bill run.

              '
            type: string
          invoiceDate:
            description: 'The invoice date for this bill run, only valid for ad-hoc bill runs.

              '
            format: date
            type: string
          invoiceDateOffset:
            description: 'The offset compared to bill run execution date, only valid for scheduled bill runs.

              '
            type: integer
          name:
            description: 'The name of the bill run.

              '
            type: string
          noEmailForZeroAmountInvoice:
            description: "Whether to suppress emails for invoices with zero total amount generated in this bill run after the bill run is complete. \n"
            type: boolean
          organizationLabels:
            description: "The organization(s) that the run is created for. \n\nNote: This field is available only when the Multi-Org feature is enabled.\n"
            items:
              properties:
                organizationId:
                  description: 'The organization ID.

                    '
                  type: string
                organizationName:
                  description: 'The organization name.

                    '
                  type: string
              type: object
            type: array
          schedule:
            $ref: '#/components/schemas/BillRunScheduleResponseType'
          scheduledExecutionTime:
            description: 'The scheduled execution time for a bill run.

              '
            format: date-time
            type: string
          status:
            description: 'The status of the bill run.

              '
            enum:
            - Pending
            - Processing
            - Completed
            - Error
            - Canceled
            - Posted
            - PostInProgress
            - CancelInProgress
            - RemoveInProgress
            - Paused
            type: string
          targetDate:
            description: 'The target date for this bill run, only valid for ad-hoc bill runs.

              '
            format: date
            type: string
          targetDateOffset:
            description: 'The offset compared to bill run execution date, only valid for scheduled bill runs.

              '
            type: integer
          updatedById:
            description: 'The ID of the user who last updated the bill run.

              '
            type: string
          updatedDate:
            description: 'The date and time when the bill run was last updated.

              '
            format: date-time
            type: string
        type: object
      example:
        autoEmail: false
        autoPost: false
        autoRenewal: false
        batches: null
        billCycleDay: null
        billRunFilters:
        - accountId: 2c9081a03c63c94c013c66688a2c00bf
          filterType: Subscription
          subscriptionId: 402882297e387c51017e38a245c313db
        billRunNumber: BR-00000016
        chargeTypeToExclude:
        - OneTime
        - Usage
        createdById: ff808081298c6e5401298c7274a40005
        createdDate: '2022-01-24 19:58:27'
        id: 2c9890077e8a8490017e8bf3a5171a43
        invoiceDate: '2020-02-01'
        invoiceDateOffset: null
        name: test
        noEmailForZeroAmountInvoice: false
        schedule: null
        scheduledExecutionTime: null
        status: Pending
        success: true
        targetDate: '2020-02-01'
        targetDateOffset: null
        updatedById: ff808081298c6e5401298c7274a40005
        updatedDate: '2022-01-24 19:58:27'
    BillRunScheduleResponseType:
      allOf:
      - description: 'Container for information about the scheduled bill run.

          '
        properties:
          repeatFrom:
            description: 'The start date of the scheduled bill run.

              '
            format: date
            type: string
          repeatTo:
            description: 'The end date of of the scheduled bill run.

              '
            format: date
            type: string
          repeatType:
            description: 'The repeat type of the bill run.

              '
            enum:
            - None
            - Daily
            - Weekly
            - Monthly
            type: string
          runTime:
            description: 'The scheduled run time (hour) of day.


              **Values:** 0 - 23

              '
            type: integer
          weeklyOnDay:
            description: 'The repeat day in a week.

              '
            items:
              enum:
              - Mon
              - Tue
              - Wed
              - Thu
              - Fri
              - Sat
              - Sun
              type: string
            type: array
        type: object
      title: schedule
    BillRunScheduleRequestType:
      allOf:
      - description: 'Container for information about the scheduled bill run.

          '
        properties:
          repeatFrom:
            description: 'The start date of the scheduled bill run.

              '
            format: date
            type: string
          repeatTo:
            description: 'The end date of of the scheduled bill run.

              '
            format: date
            type: string
          repeatType:
            description: 'The repeat type of the bill run.

              '
            enum:
            - None
            - Daily
            - Weekly
            - Monthly
            type: string
          runTime:
            description: 'The scheduled run time (hour) of day.


              **Values:** 0 - 23

              '
            type: integer
          weeklyOnDay:
            description: "The repeat day in a week. \n\nThis field is required if you set `repeatType` field to `Weekly`.\n"
            items:
              enum:
              - Mon
              - Tue
              - Wed
              - Thu
              - Fri
              - Sat
              - Sun
              type: string
            type: array
        required:
        - repeatFrom
        - repeatType
        - runTime
        type: object
      title: schedule
    BillRunFilterResponseType:
      allOf:
      - properties:
          accountId:
            description: 'The target account of the bill run.

              '
            type: string
          filterType:
            description: 'To create bill run at account level or subscription level.

              '
            enum:
            - Account
            - Subscription
            type: string
          subscriptionId:
            description: "The target subscripiton ID of the account. \n"
            type: string
        type: object
      title: billRunFilters
    CommonResponseType:
      properties:
        processId:
          description: 'The Id of the process that handle the operation.

            '
          type: string
        reasons:
          items:
            properties:
              code:
                description: 'The error code of response.

                  '
                type: string
              message:
                description: 'The detail information of the error response

                  '
                type: string
            type: object
          type: array
        success:
          description: 'Indicates whether the call succeeded.

            '
          type: boolean
      type: object
    POSTCreateBillRunRequestType:
      allOf:
      - properties:
          autoEmail:
            default: false
            description: 'Whether to automatically send emails after Auto-Post is complete.


              **Note:** To use this field, you must first set the <a href="https://knowledgecenter.zuora.com/CB_Billing/Billing_Settings/Define_Billing_Rules" target="_blank">Support Bill Run Auto-Post?</a> billing rule to **Yes** through the Zuora UI.

              '
            type: boolean
          autoPost:
            default: false
            description: 'Whether to automatically post the bill run after the bill run is created.


              **Note:** To use this field, you must first set the <a href="https://knowledgecenter.zuora.com/CB_Billing/Billing_Settings/Define_Billing_Rules" target="_blank">Support Bill Run Auto-Post?</a> billing rule to **Yes** through the Zuora UI.

              '
            type: boolean
          autoRenewal:
            default: false
            description: 'Whether to automatically renew auto-renew subscriptions that are up for renewal.

              '
            type: boolean
          batches:
            description: "The batch of accounts for this bill run. \n\nYou can only specify either this field or the `billRunFilters` field.\n\n**Values:** `AllBatches` or an array of `Batch*n*` where *n* is one of numbers 1 - 50, for example, `Batch7`.\n\n**Note**: By default, you have 50 configurable account batches. To increase the limit to 200 batches, you must have the <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Performance_Booster_Elite\" target=\"_blank\">Performance Booster Elite</a> package.\n"
            items:
              type: string
            type: array
          billCycleDay:
            description: "The day of the bill cycle. This field is only valid if the `batches` field is specified.\n\n**Values:** \n- `AllBillCycleDays` or one of numbers 1 - 31 for an ad-hoc bill run\n- `AllBillCycleDays`, one of numbers 1 - 31, or `AsRunDay` for a scheduled bill run\n"
            type: string
          billRunFilters:
            description: 'The target account or subscriptions for this bill run. You can only specify either this field or the `batches` field.

              '
            items:
              $ref: '#/components/schemas/BillRunFilterRequestType'
            type: array
          billRunType:
            description: "The type of the bill run. If you do not specify any value for this field, the default value is `Regular`.\n\n- You can use this field only if the \"Catch-Up Bill Run\" feature is enabled. \n- You must specify this field to create a catch up bill run.\n\n**Values:** \n- `Regular`\n- `CatchUp`\n"
            type: string
          chargeTypeToExclude:
            description: 'The types of the charges to be excluded from the generation of billing documents. You can specify at most two charge types in the array.

              '
            items:
              enum:
              - OneTime
              - Recurring
              - Usage
              type: string
            type: array
          invoiceDate:
            description: "The invoice date for the bill run.\n\n- When creating an ad-hoc bill run, if you do not specify any value for this field, the default value is the current date.\n- When creating a scheduled bill run, if you do not specify any value for this field, the invoice date is the value of the `repeatFrom` field. \n"
            format: date
            type: string
          name:
            description: 'The name of the bill run.

              '
            type: string
          noEmailForZeroAmountInvoice:
            default: false
            description: "Whether to suppress emails for invoices with zero total amount generated in this bill run after the bill run is complete. \n\nIt is best practice to not send emails for invoices with zero amount.\n"
            type: boolean
          organizationLabels:
            description: "The organization(s) that the bill run is created for. \n\nFor each item in the array, either the `organizationId` or the `organizationName` field is required.\n\nThis field is only required when you have already turned on Multi-Org feature.\n"
            items:
              properties:
                organizationId:
                  description: 'The organization ID.

                    '
                  type: string
                organizationName:
                  description: 'The organization name.

                    '
                  type: string
              type: object
            type: array
          schedule:
            $ref: '#/components/schemas/BillRunScheduleRequestType'
          targetDate:
            description: "The target date for this bill run. \n\n- You must specify this field when creating an ad-hoc bill run.\n- For scheduled bill runs, if you do not specify any value for this field, the target date is the value of the `repeatFrom` field.\n"
            format: date
            type: string
        type: object
      example:
        autoEmail: false
        autoPost: false
        autoRenewal: false
        billRunFilters:
        - accountId: 2c9081a03c63c94c013c66688a2c00bf
          filterType: Subscription
          subscriptionId: 402882297e387c51017e38a245c313db
        chargeTypeToExclude:
        - OneTime
        - Usage
        invoiceDate: '2020-02-01'
        name: test
        noEmailForZeroAmountInvoice: false
        targetDate: '2020-02-01'
  parameters:
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Authorization_OAuth_optional:
      name: Authorization
      in: header
      required: false
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
