openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Taxation Items API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Taxation Items
  description: 'The TaxationItem object is used to add a tax amount to an invoice item. In the typical use case, the tax amount that you specify in the object is calculated by Z-Tax or a third-party tax engine such as Avalara or Connect tax engine.


    Changes that you make with this object affect the product charges in your product catalog, but not the charges in existing subscriptions.'
paths:
  /v1/taxationitems/{id}:
    put:
      description: Updates a specific taxation item by ID.
      summary: Update a taxation item
      operationId: PUT_TaxationItem
      tags:
      - Taxation Items
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETTaxationItemType'
              example:
                createdById: 402881e522cf4f9b0122cf5d82860002
                createdDate: '2017-02-27 18:16:24'
                exemptAmount: 0
                id: 402890555a7e9791015a7f12364e0004
                memoItemId: 402890555a7e9791015a7f1235f50003
                sourceTaxItemId: 402890555a7d4022015a7db254e200c1
                jurisdiction: CALIFORNIA
                locationCode: '06'
                name: STATE TAX
                taxAmount: 1
                taxCode: ServiceTaxCode
                taxCodeDescription: This is tax code description!
                taxDate: '2016-06-05'
                taxRate: 0.0625
                taxRateDescription: This is tax rate description!
                taxRateType: Percentage
                updatedById: 402881e522cf4f9b0122cf5d82860002
                updatedDate: '2017-02-28 17:53:11'
                financeInformation:
                  onAccountAccountingCode: Check
                  onAccountAccountingCodeType: Cash
                  salesTaxPayableAccountingCode: null
                  salesTaxPayableAccountingCodeType: null
                success: true
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - in: path
        name: id
        required: true
        description: 'The unique ID of a taxation item.

          '
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PUTTaxationItemType'
        required: true
    get:
      description: Retrieves the information about a specific taxation item by ID.
      summary: Retrieve a taxation item
      operationId: GET_TaxationItem
      tags:
      - Taxation Items
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETTaxationItemType'
              example:
                createdById: 402881e522cf4f9b0122cf5d82860002
                createdDate: '2017-02-27 11:52:03'
                exemptAmount: 0
                id: 402890555a7d4022015a7db254e200c8
                memoItemId: 402890555a7d4022015a7db254d800c7
                sourceTaxItemId: 402890555a7d4022015a7db254e200c1
                jurisdiction: null
                locationCode: null
                name: my tax
                taxAmount: 1
                taxCode: ZtaxCode
                taxCodeDescription: ''
                taxDate: '2017-02-27'
                taxRate: 5
                taxRateDescription: null
                taxRateType: FlatFee
                updatedById: 402881e522cf4f9b0122cf5d82860002
                updatedDate: '2017-02-27 11:52:03'
                financeInformation:
                  onAccountAccountingCode: null
                  onAccountAccountingCodeType: null
                  salesTaxPayableAccountingCode: null
                  salesTaxPayableAccountingCodeType: null
                success: true
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - in: path
        name: id
        required: true
        description: 'The unique ID of a taxation item.

          '
        schema:
          type: string
    delete:
      description: Deletes a specific taxation item by ID.
      summary: Delete a taxation item
      operationId: DELETE_TaxationItem
      tags:
      - Taxation Items
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponseType'
              example:
                success: true
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - in: path
        name: id
        required: true
        description: 'The unique ID of a taxation item.

          '
        schema:
          type: string
  /v1/object/taxation-item:
    post:
      summary: 'CRUD: Create a taxation item'
      operationId: Object_POSTTaxationItem
      description: ''
      tags:
      - Taxation Items
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_REQUEST_rejectUnknownFields'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      responses:
        '200':
          description: ''
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProxyCreateOrModifyResponse'
              example:
                Success: true
                Id: 2c93808457d787030157e0306f413a96
        '400':
          description: ''
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProxyBadRequestResponse'
              example:
                Errors:
                - Code: INVALID_VALUE
                  Message: The account number 123xProxy is invalid.
                Success: false
        '401':
          description: ''
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
            WWW-Authenticate:
              description: 'The value of this header is:


                ```

                Basic realm=Zuora API, ZSession realm=Zuora API, Bearer realm=Zuora API

                ```

                '
              schema:
                type: string
                enum:
                - Basic realm=Zuora API, ZSession realm=Zuora API, Bearer realm=Zuora API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProxyUnauthorizedResponse'
              example:
                message: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProxyCreateTaxationItem'
        required: true
components:
  parameters:
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_REQUEST_rejectUnknownFields:
      name: rejectUnknownFields
      in: query
      required: false
      description: "Specifies whether the call fails if the request body contains unknown fields.\nWith `rejectUnknownFields` set to `true`, Zuora returns a 400 response if\nthe request body contains unknown fields. The body of the 400 response is:\n\n```json\n{\n    \"message\": \"Error - unrecognised fields\"\n}\n```\n\nBy default, Zuora ignores unknown fields in the request body.\n"
      schema:
        type: boolean
        default: false
    GLOBAL_HEADER_Authorization_OAuth_optional:
      name: Authorization
      in: header
      required: false
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
  schemas:
    ProxyCreateOrModifyResponse:
      properties:
        Id:
          description: ''
          type: string
        Success:
          description: ''
          type: boolean
      type: object
    ProxyCreateTaxationItem:
      allOf:
      - properties:
          AccountingCode:
            description: ' The Chart of Accounts '
            type: string
          ExemptAmount:
            description: ' The calculated tax amount excluded due to the exemption.

              **Character limit**: 16 **Values**: a decimal value '
            format: double
            type: number
          InvoiceItemId:
            description: ' The ID of the specific invoice item that the taxation information applies to.

              **Character limit**: 32 **Values**: a valid invoice item ID '
            type: string
          Jurisdiction:
            description: ' The jurisdiction that applies the tax or VAT. This value is typically a state, province, county, or city.

              **Character limit**: 32 **Values**: a string of 32 characterrs or fewer '
            type: string
          LocationCode:
            description: ' The identifier for the location based on the value of the `TaxCode` field.

              **Character limit**: 32 **Values**: automatically generated '
            type: string
          Name:
            description: ' The name of the tax rate, such as sales tax or GST. This name is displayed on invoices.

              **Character limit**: 128 **Values**: a string of 128 characters or fewer '
            type: string
          TaxAmount:
            description: ' The amount of the tax applied to the charge.

              **Character limit**: 16 **Values**: a decimal value '
            format: double
            type: number
          TaxCode:
            description: ' The tax code identifies which tax rules and tax rates to apply to a specific charge.

              **Character limit**: 32 **Values**: a string of 32 characters or fewer '
            type: string
          TaxCodeDescription:
            description: ' The description for the tax code.

              **Character limit**: 255 **Values**: a string of 255 characters or fewer '
            type: string
          TaxDate:
            description: ' The date that the tax is applied to the charge, in `yyyy-mm-dd` format.

              **Character limit**: 29 '
            format: date
            type: string
          TaxRate:
            description: ' The tax rate applied to the charge.

              **Character limit**: 16 **Values**: a valid decimal value '
            format: double
            type: number
          TaxRateDescription:
            description: ' The description of the tax rate.

              **Character limit**: 255 **Values**: a string of 255 characters or fewer '
            type: string
          TaxRateType:
            description: ' The type of the tax rate applied to the charge.

              **Character limit**: 10 **Values**: `Percentage`, `FlatFee` '
            type: string
        required:
        - InvoiceItemId
        - Jurisdiction
        - Name
        - TaxAmount
        - TaxRate
        - TaxDate
        - TaxRateType
        type: object
      - $ref: '#/components/schemas/TaxationItemObjectCustomFields'
      example:
        AccountingCode: Usage Revenue
        ExemptAmount: 50
        InvoiceItemId: 2c93808457d787030157e0306cd43a88
        Jurisdiction: test
        LocationCode: code - 001
        Name: test
        TaxAmount: 3
        TaxCode: taxcode
        TaxCodeDescription: description
        TaxDate: '2016-10-20'
        TaxMode: TaxExclusive
        TaxRate: 3
        TaxRateDescription: test
        TaxRateType: FlatFee
    ProxyBadRequestResponse:
      properties:
        Errors:
          items:
            properties:
              Code:
                description: ''
                type: string
              Message:
                description: ''
                type: string
            type: object
          type: array
        Success:
          description: ''
          type: boolean
      type: object
    PUTTaxationItemType:
      allOf:
      - properties:
          exemptAmount:
            description: 'The calculated tax amount excluded due to the exemption.

              '
            format: double
            type: number
          financeInformation:
            description: 'Container for the finance information related to the taxation item.

              '
            properties:
              onAccountAccountingCode:
                description: 'The accounting code that maps to an on account in your accounting system.

                  '
                maxLength: 100
                minLength: 0
                type: string
              salesTaxPayableAccountingCode:
                description: 'The accounting code for the sales taxes payable.

                  '
                maxLength: 100
                minLength: 0
                type: string
            type: object
          jurisdiction:
            description: 'The jurisdiction that applies the tax or VAT. This value is typically a state, province, county, or city.

              '
            type: string
          locationCode:
            description: "The identifier for the location based on the value of the `taxCode` field. \n"
            type: string
          name:
            description: 'The name of the taxation item to be updated.

              '
            type: string
          taxAmount:
            description: 'The amount of the tax applied to the credit or debit memo.

              '
            format: double
            type: number
          taxCode:
            description: 'The tax code identifies which tax rules and tax rates to apply to a specific credit or debit memo.

              '
            type: string
          taxCodeDescription:
            description: 'The description of the tax code.

              '
            type: string
          taxDate:
            description: 'The date when the tax is applied to the credit or debit memo.

              '
            format: date
            type: string
          taxRate:
            description: 'The tax rate applied to the credit or debit memo.

              '
            format: double
            type: number
          taxRateDescription:
            description: "The description of the tax rate. \n"
            type: string
          taxRateType:
            description: 'The type of the tax rate applied to the credit or debit memo.

              '
            enum:
            - Percentage
            - FlatFee
            type: string
        type: object
      - $ref: '#/components/schemas/TaxationItemObjectCustomFields'
      example:
        exemptAmount: 0.0
        financeInformation:
          onAccountAccountingCode: Check
          salesTaxPayableAccountingCode: ''
        jurisdiction: CALIFORNIA
        locationCode: '06'
        name: STATE TAX
        taxAmount: 1.0
        taxCode: ServiceTaxCode
        taxCodeDescription: This is tax code description!
        taxDate: '2016-06-05'
        taxRate: 0.0625
        taxRateDescription: This is tax rate description!
        taxRateType: Percentage
    ProxyUnauthorizedResponse:
      properties:
        message:
          description: 'Error message.


            If the error message is "Authentication error", ensure that the `Authorization` request header contains valid authentication credentials, then retry the request. See [Authentication](/rest-api/general-concepts/authentication/) for more information.


            If the error message is "Failed to get user info", retry the request.

            '
          type: string
      type: object
    TaxationItemObjectCustomFields:
      additionalProperties:
        description: 'Custom fields of the Taxation Item object. The name of each custom field has the form <code>*customField*__c</code>. Custom field names are case sensitive. See [Manage Custom Fields](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Manage_Custom_Fields) for more information.

          '
      description: 'Container for custom fields of a Taxation Item object.

        '
      title: taxationItemFieldsCustom
      type: object
    CommonResponseType:
      properties:
        processId:
          description: 'The Id of the process that handle the operation.

            '
          type: string
        reasons:
          items:
            properties:
              code:
                description: 'The error code of response.

                  '
                type: string
              message:
                description: 'The detail information of the error response

                  '
                type: string
            type: object
          type: array
        success:
          description: 'Indicates whether the call succeeded.

            '
          type: boolean
      type: object
    GETTaxationItemType:
      allOf:
      - properties:
          createdById:
            description: "The ID of the Zuora user who created the taxation item. \n"
            type: string
          createdDate:
            description: 'The date and time when the taxation item was created in the Zuora system, in `yyyy-mm-dd hh:mm:ss` format.

              '
            format: date-time
            type: string
          exemptAmount:
            description: 'The calculated tax amount excluded due to the exemption.

              '
            format: double
            type: number
          financeInformation:
            description: 'Container for the finance information related to the taxation item.

              '
            properties:
              onAccountAccountingCode:
                description: 'The accounting code that maps to an on account in your accounting system.

                  '
                type: string
              onAccountAccountingCodeType:
                description: 'The type of the accounting code that maps to an on account in your accounting system.

                  '
                type: string
              salesTaxPayableAccountingCode:
                description: 'The accounting code for the sales taxes payable.

                  '
                type: string
              salesTaxPayableAccountingCodeType:
                description: 'The type of the accounting code for the sales taxes payable.

                  '
                type: string
            type: object
          id:
            description: 'The ID of the taxation item.

              '
            type: string
          jurisdiction:
            description: 'The jurisdiction that applies the tax or VAT. This value is typically a state, province, county, or city.

              '
            type: string
          locationCode:
            description: "The identifier for the location based on the value of the `taxCode` field. \n"
            type: string
          memoItemId:
            description: 'The ID of the credit or debit memo associated with the taxation item.

              '
            type: string
          name:
            description: 'The name of the taxation item.

              '
            type: string
          sourceTaxItemId:
            description: 'The ID of the taxation item of the invoice, which the credit or debit memo is created from.

              '
            type: string
          success:
            description: Returns `true` if the request was processed successfully.
            type: boolean
          taxAmount:
            description: 'The amount of the tax applied to the credit or debit memo.

              '
            format: double
            type: number
          taxCode:
            description: 'The tax code identifies which tax rules and tax rates to apply to a specific credit or debit memo.

              '
            type: string
          taxCodeDescription:
            description: 'The description of the tax code.

              '
            type: string
          taxDate:
            description: 'The date when the tax is applied to the credit or debit memo.

              '
            format: date
            type: string
          taxRate:
            description: 'The tax rate applied to the credit or debit memo.

              '
            format: double
            type: number
          taxRateDescription:
            description: 'The description of the tax rate.

              '
            type: string
          taxRateType:
            description: 'The type of the tax rate applied to the credit or debit memo.

              '
            enum:
            - Percentage
            - FlatFee
            type: string
          updatedById:
            description: 'The ID of the Zuora user who last updated the taxation item.

              '
            type: string
          updatedDate:
            description: "The date and time when the taxation item was last updated, in `yyyy-mm-dd hh:mm:ss` format. \n"
            format: date-time
            type: string
        type: object
      - $ref: '#/components/schemas/TaxationItemObjectCustomFields'
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
