openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Sequence Sets API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Sequence Sets
  description: 'You can create billing document sequence sets through the REST API or the Zuora UI, allowing distinct numbering sequences for billing documents, payments, and refunds.


    To create a billing document sequence set through the Zuora UI, see Create Billing Document Sequence Sets for more information.'
paths:
  /v1/sequence-sets:
    post:
      summary: Create sequence sets
      operationId: POST_SequenceSets
      description: 'Creates sequence sets, allowing distinct numbering sequences for billing documents, payments, and refunds. Billing documents include invoices, credit memos, and debit memos.


        You can create a maximum of 100 sequence sets in one single request. A sequence set comprises a set of custom prefixes and starting numbers that are used for billing documents to generate, and payments and refunds to create.


        See Prefix and Numbering Configuration for Billing Documents for more information about limitations.


        **Note**: The Credit and Debit Memos feature is only available if you have Invoice Settlement enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see Invoice Settlement Enablement and Checklist Guide for more information.'
      tags:
      - Sequence Sets
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/POSTSequenceSetsResponse'
              example:
                success: true
                sequenceSets:
                - name: FR
                  id: 402892c74c9193cd014c96bbe7c101f9
                  invoice:
                    prefix: FINV
                    startNumber: 10
                  creditMemo:
                    prefix: FCM
                    startNumber: 10
                  debitMemo:
                    prefix: FDM
                    startNumber: 10
                  payment:
                    prefix: FP-
                    startNumber: 10
                  refund:
                    prefix: FR-
                    startNumber: 10
                - name: ITA
                  id: 402892c74c9193cd014c96bbe7c201f9
                  invoice:
                    prefix: IINV
                    startNumber: 10
                  creditMemo:
                    prefix: ICM
                    startNumber: 10
                  debitMemo:
                    prefix: IDM
                    startNumber: 10
                  payment:
                    prefix: IP-
                    startNumber: 10
                  refund:
                    prefix: IR-
                    startNumber: 10
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTSequenceSetsRequest'
        required: true
    get:
      summary: List sequence sets
      operationId: GET_SequenceSets
      description: 'Retrieves information about all sequence sets configured for billing documents, payments, and refunds. Billing documents include invoices, credit memos, and debit memos.


        You can use query parameters to restrict the data returned in the response.


        **Note**: The Credit and Debit Memos feature is only available if you have Invoice Settlement enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see Invoice Settlement Enablement and Checklist Guide for more information.'
      tags:
      - Sequence Sets
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_REQUEST_pageSize'
      - $ref: '#/components/parameters/GLOBAL_REQUEST_page'
      - name: name
        in: query
        description: 'The name of a specific sequence set.

          '
        required: false
        schema:
          type: string
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETSequenceSetsResponse'
              example:
                sequenceSets:
                - name: DEFAULT
                  id: 2c98906c69be199c0169be74ed210afd
                  invoice:
                    prefix: INV
                    startNumber: 10
                  creditMemo:
                    prefix: CM
                    startNumber: 11
                  debitMemo:
                    prefix: DM
                    startNumber: 12
                  payment:
                    prefix: P-
                    startNumber: 13
                  refund:
                    prefix: R-
                    startNumber: 14
                - name: FR
                  id: 2c98906c69be199c0169be74ed211afd
                  invoice:
                    prefix: FINV
                    startNumber: 10
                  creditMemo:
                    prefix: FCM
                    startNumber: 11
                  debitMemo:
                    prefix: FDM
                    startNumber: 12
                  payment:
                    prefix: FP-
                    startNumber: 13
                  refund:
                    prefix: FR-
                    startNumber: 14
                - name: ITA
                  id: 2c98906c69be199c0169be74ed212afd
                  invoice:
                    prefix: ITAINV
                    startNumber: 10
                  creditMemo:
                    prefix: ITACM
                    startNumber: 11
                  debitMemo:
                    prefix: ITADM
                    startNumber: 12
                  payment:
                    prefix: ITAP-
                    startNumber: 13
                  refund:
                    prefix: ITAR-
                    startNumber: 14
                success: true
  /v1/sequence-sets/{id}:
    put:
      summary: Update a sequence set
      operationId: PUT_SequenceSet
      description: 'Updates a specific sequence set configured for billing documents, payments, and refunds. Billing documents include invoices, credit memos, and debit memos.


        **Note**: The Credit and Debit Memos feature is only available if you have Invoice Settlement enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see Invoice Settlement Enablement and Checklist Guide for more information.'
      tags:
      - Sequence Sets
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: id
        in: path
        description: 'The ID of the sequence set to update.

          '
        required: true
        schema:
          type: string
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PUTSequenceSetResponse'
              example:
                success: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PUTSequenceSetRequest'
    get:
      summary: Retrieve a sequence set
      operationId: GET_SequenceSet
      description: 'Retrieves information about a specific sequence set configured for billing documents, payments, and refunds. Billing documents include invoices, credit memos, and debit memos


        **Note**: The Credit and Debit Memos feature is only available if you have Invoice Settlement enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see Invoice Settlement Enablement and Checklist Guide for more information.'
      tags:
      - Sequence Sets
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: id
        in: path
        description: 'The ID of the sequence set to retrieve information about.

          '
        required: true
        schema:
          type: string
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETSequenceSetResponse'
              example:
                name: FR
                invoice:
                  prefix: FINV
                  startNumber: 10
                creditMemo:
                  prefix: FCM
                  startNumber: 11
                debitMemo:
                  prefix: FDM
                  startNumber: 12
                payment:
                  prefix: FP-
                  startNumber: 13
                refund:
                  prefix: FR-
                  startNumber: 14
                success: true
    delete:
      summary: Delete a sequence set
      operationId: DELETE_SequenceSet
      description: 'Deletes a specific sequence set configured for billing documents, payments, and refunds. Billing documents include invoices, credit memos, and debit memos.


        **Note**: The Credit and Debit Memos feature is only available if you have Invoice Settlement enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see Invoice Settlement Enablement and Checklist Guide for more information.'
      tags:
      - Sequence Sets
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - name: id
        in: path
        description: 'The ID of the sequence set to delete.

          '
        required: true
        schema:
          type: string
      responses:
        200:
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponseType'
              example:
                success: true
components:
  parameters:
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_REQUEST_pageSize:
      name: pageSize
      in: query
      required: false
      description: 'The number of records returned per page in the response.

        '
      schema:
        type: integer
        default: 20
        maximum: 40
    GLOBAL_HEADER_Authorization_OAuth_optional:
      name: Authorization
      in: header
      required: false
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
    GLOBAL_REQUEST_page:
      name: page
      in: query
      required: false
      description: 'The index number of the page that you want to retrieve. This parameter is dependent on `pageSize`. You must set `pageSize` before specifying `page`. For example, if you set `pageSize` to `20` and `page` to `2`, the 21st to 40th records are returned in the response.

        '
      schema:
        type: integer
        default: 1
        minimum: 1
  schemas:
    PUTSequenceSetResponse:
      description: ''
      properties:
        success:
          description: 'Indicates whether the call succeeded.

            '
          type: boolean
      type: object
    PaymentEntityPrefix:
      description: 'Container for the prefix and starting number of payments.

        '
      properties:
        prefix:
          description: 'The prefix of payments.

            '
          example: P-
          type: string
        startNumber:
          description: 'The starting number of payments.

            '
          example: 10
          type: integer
      title: payment
      type: object
    POSTSequenceSetsResponse:
      description: ''
      properties:
        sequenceSets:
          description: 'Array of sequence sets configured for billing documents, payments, and refunds.

            '
          items:
            $ref: '#/components/schemas/GETSequenceSetResponse'
          type: array
        success:
          description: 'Indicates whether the call succeeded.

            '
          example: true
          type: boolean
      type: object
    RefundEntityPrefix:
      description: 'Container for the prefix and starting number of refunds.

        '
      properties:
        prefix:
          description: 'The prefix of refunds.

            '
          example: R-
          type: string
        startNumber:
          description: 'The starting number of refunds.

            '
          example: 10
          type: integer
      title: refund
      type: object
    InvoiceEntityPrefix:
      description: 'Container for the prefix and starting document number of invoices.

        '
      properties:
        prefix:
          description: 'The prefix of invoices.

            '
          example: INV
          type: string
        startNumber:
          description: 'The starting document number of invoices.

            '
          example: 10
          type: integer
      title: Invoice
      type: object
    POSTSequenceSetsRequest:
      description: ''
      example:
        sequenceSets:
        - creditMemo:
            prefix: FCM
            startNumber: 10
          debitMemo:
            prefix: FDM
            startNumber: 10
          invoice:
            prefix: FINV
            startNumber: 10
          name: FR
          payment:
            prefix: FP-
            startNumber: 10
          refund:
            prefix: FR-
            startNumber: 10
        - creditMemo:
            prefix: ICM
            startNumber: 10
          debitMemo:
            prefix: IDM
            startNumber: 10
          invoice:
            prefix: IINV
            startNumber: 10
          name: ITA
          payment:
            prefix: IP-
            startNumber: 10
          refund:
            prefix: IR-
            startNumber: 10
      properties:
        sequenceSets:
          description: 'Array of sequence sets configured for billing documents, payments, and refunds.

            '
          items:
            $ref: '#/components/schemas/POSTSequenceSetRequest'
          type: array
      type: object
    DebitMemoEntityPrefix:
      description: 'Container for the prefix and starting document number of debit memos.


        **Note:** This field is only available if you have the Invoice Settlement feature enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see [Invoice Settlement Enablement and Checklist Guide](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement/Invoice_Settlement_Migration_Checklist_and_Guide) for more information.

        '
      properties:
        prefix:
          description: 'The prefix of debit memos.

            '
          example: DM
          type: string
        startNumber:
          description: 'The starting document number of debit memos.

            '
          example: 10
          type: integer
      title: debitMemo
      type: object
    GETSequenceSetsResponse:
      description: ''
      properties:
        sequenceSets:
          description: 'Array of sequence sets configured for billing documents, payments, and refunds.

            '
          items:
            $ref: '#/components/schemas/GETSequenceSetResponse'
          type: array
        success:
          description: 'Indicates whether the call succeeded.

            '
          type: boolean
      type: object
    POSTSequenceSetRequest:
      description: ''
      properties:
        creditMemo:
          $ref: '#/components/schemas/CreditMemoEntityPrefix'
        debitMemo:
          $ref: '#/components/schemas/DebitMemoEntityPrefix'
        invoice:
          $ref: '#/components/schemas/InvoiceEntityPrefix'
        name:
          description: 'The name of the sequence set to configure for billing documents, payments, and refunds.

            '
          example: FRANCE
          type: string
        payment:
          $ref: '#/components/schemas/PaymentEntityPrefix'
        refund:
          $ref: '#/components/schemas/RefundEntityPrefix'
      required:
      - name
      - invoice
      - creditMemo
      - debitMemo
      title: sequenceSets
      type: object
    CommonResponseType:
      properties:
        processId:
          description: 'The Id of the process that handle the operation.

            '
          type: string
        reasons:
          items:
            properties:
              code:
                description: 'The error code of response.

                  '
                type: string
              message:
                description: 'The detail information of the error response

                  '
                type: string
            type: object
          type: array
        success:
          description: 'Indicates whether the call succeeded.

            '
          type: boolean
      type: object
    PUTSequenceSetRequest:
      description: ''
      example:
        creditMemo:
          prefix: FR-CM
        invoice:
          startNumber: 100
        name: FR
        payment:
          prefix: FR-P-
      properties:
        creditMemo:
          $ref: '#/components/schemas/CreditMemoEntityPrefix'
        debitMemo:
          $ref: '#/components/schemas/DebitMemoEntityPrefix'
        invoice:
          $ref: '#/components/schemas/InvoiceEntityPrefix'
        name:
          description: 'The name of the sequence set configured for billing documents, payments, and refunds.

            '
          type: string
        payment:
          $ref: '#/components/schemas/PaymentEntityPrefix'
        refund:
          $ref: '#/components/schemas/RefundEntityPrefix'
      type: object
    CreditMemoEntityPrefix:
      description: 'Container for the prefix and starting document number of credit memos.


        **Note:** This field is only available if you have the Invoice Settlement feature enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see [Invoice Settlement Enablement and Checklist Guide](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement/Invoice_Settlement_Migration_Checklist_and_Guide) for more information.

        '
      properties:
        prefix:
          description: 'The prefix of credit memos.

            '
          example: CM
          type: string
        startNumber:
          description: 'The starting document number of credit memos.

            '
          example: 10
          type: integer
      title: creditMemo
      type: object
    GETSequenceSetResponse:
      description: ''
      properties:
        creditMemo:
          $ref: '#/components/schemas/CreditMemoEntityPrefix'
        debitMemo:
          $ref: '#/components/schemas/DebitMemoEntityPrefix'
        id:
          description: 'The unique ID of the sequence set. For example, 402892c74c9193cd014c96bbe7c101f9.

            '
          type: string
        invoice:
          $ref: '#/components/schemas/InvoiceEntityPrefix'
        name:
          description: 'The name of the sequence set.

            '
          type: string
        payment:
          $ref: '#/components/schemas/PaymentEntityPrefix'
        refund:
          $ref: '#/components/schemas/RefundEntityPrefix'
      title: sequenceSets
      type: object
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
