openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Billing Documents API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Billing Documents
  description: 'Billing documents include invoices, credit memos, and debit memos.


    **Note**: Credit memos and debit memos are only available if you have the Invoice Settlement feature enabled.'
paths:
  /v1/accounts/{key}/billing-documents/generate:
    post:
      description: 'Generates draft or posted billing documents for a specified account. You can also generate billing documents for specified subscriptions of a specified account. The billing documents contain invoices and credit memos. To generate credit memos, you must have the Invoice Settlement feature enabled.


        **Note**: You cannot generate billing documents for cancelled or suspended subscriptions.'
      summary: Generate billing documents by account ID
      operationId: POST_GenerateBillingDocuments
      tags:
      - Billing Documents
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateBillingDocumentResponseType'
              example:
                invoices:
                - id: 402890555c33b44b015c33bfe9c70044
                - id: 402890555c33b44b015c33bfe9d70046
                creditMemos:
                - id: 402890555c33b44b015c33bfe947003c
                - id: 402890555c33b44b015c33bfe93c003a
                success: true
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - in: path
        name: key
        description: 'The ID or number of the customer account that billing documents are generated for. For example, 8a8082e65b27f6c3015ba3e326b26419 or AC0000001.

          '
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostGenerateBillingDocumentType'
        required: true
  /v1/billing-documents:
    get:
      description: 'Retrieves the information about all billing documents associated with a specified account. The billing documents contain invoices, credit memos, and debit memos.


        To retrieve information about credit memos and debit memos, you must have the Invoice Settlement feature enabled.


        You can use query parameters to restrict the data returned in the response.


        Examples:

        - /billing-documents?accountId=4028905f5e4feb38015e50af9aa002d1&sort=+documentDate

        - /billing-documents?accountId=4028905f5e4feb38015e50af9aa002d1&status=Posted

        - /billing-documents?accountNumber=A00000001&sort=+documentDate

        - /billing-documents?accountNumber=A00000001&status=Posted'
      summary: List billing documents for an account
      operationId: GET_BillingDocuments
      tags:
      - Billing Documents
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - $ref: '#/components/parameters/GLOBAL_REQUEST_page'
      - $ref: '#/components/parameters/GLOBAL_REQUEST_pageSize'
      - name: accountId
        in: query
        required: false
        description: 'The ID of the customer account that the billing documents are associated with.


          **Note**: When retrieving information about all billing documents associated with an account, you must specify either `accountId` or `accountNumber` in the query parameters.

          '
        schema:
          type: string
          format: uuid
      - name: accountNumber
        in: query
        required: false
        description: 'The number of the customer account that the billing documents are associated with.


          **Note**: When retrieving information about all billing documents associated with an account, you must specify either `accountId` or `accountNumber` in the query parameters.

          '
        schema:
          type: string
          format: uuid
      - name: documentDate
        in: query
        required: false
        description: 'The date of the billing document. It represents the invoice date for invoices, credit memo date for credit memos, and debit memo date for debit memos.

          '
        schema:
          type: string
          format: date
      - name: status
        in: query
        required: false
        description: 'The status of the billing document.

          '
        schema:
          type: string
          enum:
          - Draft
          - Posted
          - Canceled
          - Error
      - name: sort
        in: query
        required: false
        description: "This parameter restricts the order of the data returned in the response. You can use this parameter to supply a dimension you want to sort on.\n\nIf you do not specify any sortable field, the response data is sorted by the `documentDate` field in descending order.\n\nA sortable field uses the following form: \n\n*operator* *field_name*\n\nYou can use at most two sortable fields in one URL path. Use a comma to separate sortable fields. For example:  *operator* *field_name*, *operator* *field_name*  \n\n*operator* is used to mark the order of sequencing. The operator is optional. If you only specify the sortable field without any operator, the response data is sorted in descending order by this field.  \n\n  - The `-` operator indicates an ascending order.\n  - The `+` operator indicates a descending order.\n\n*field_name* indicates the name of a sortable field. The supported sortable fields of this operation are as below:\n\n  - documentDate\n  - documentType\n  \nExamples:\n- /billing-documents?accountId=4028905f5e4feb38015e50af9aa002d1\n  &sort=+documentDate,-documentType\n- /billing-documents?accountId=4028905f5e4feb38015e50af9aa002d1\n  &status=Posted&sort=+documentDate&page=2&pageSize=15\n"
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingDocumentQueryResponseElementType'
              example:
                documents:
                - id: 4028905f5e4jjj015e50af9aa002d1
                  documentType: Invoice
                  documentNumber: INV-0000001
                  documentDate: '2017-10-01'
                  amount: 100
                  balance: 90
                  accountId: 4028905f5e4feb38bbb50af9aa002d1
                  accountNumber: A00000001
                  status: Posted
                - id: 4028905f5e4jbbb015e50af9aa002d1
                  documentType: CreditMemo
                  documentNumber: CM-0000001
                  documentDate: '2017-09-01'
                  amount: 100
                  balance: 90
                  accountId: 4028905f5e4feb38b111b50af9aa002d1
                  accountNumber: A00000001
                  status: Posted
                - id: 4028905f5e4jccc015e50af9aa002d1
                  documentType: DebitMemo
                  documentNumber: DM-0000001
                  documentDate: '2017-07-01'
                  amount: 100
                  balance: 90
                  accountId: 4028905f5e4feb3833b50af9aa002d1
                  accountNumber: A00000001
                  status: Posted
                success: true
      x-code-samples:
      - lang: curl
        label: Curl
        source: 'curl -X GET -H "Authorization: Bearer 6d151216ef504f65b8ff6e9e9e8356d3" -H "Content-Type: application/json" "https://rest.sandbox.eu.zuora.com/v1/billing-documents?accountId=402892c74c9193cd014c91d35b0a0132"

          '
  /v1/accounts/billing-documents/files/deletion-jobs:
    post:
      description: 'Creates an asynchronous job to permanently delete all billing document PDF files for specific accounts.


        After the deletion job is completed, all billing document PDF files are permanently deleted. To retrieve the status of a deletion job, call Retrieve a job of hard deleting billing document files.


        **Note**: This operation can be used only if you have the Billing user permission "Hard Delete Billing Document Files" enabled.'
      summary: Create a job to hard delete billing document files
      operationId: POST_BillingDocumentFilesDeletionJob
      tags:
      - Billing Documents
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/POSTBillingDocumentFilesDeletionJobResponse'
              example:
                id: 2c92c8f83dc4f752013dc72c24ee016c
                status: Pending
                success: true
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTBillingDocumentFilesDeletionJobRequest'
        required: true
  /v1/accounts/billing-documents/files/deletion-jobs/{jobId}:
    get:
      summary: Retrieve a job of hard deleting billing document files
      operationId: GET_BillingDocumentFilesDeletionJob
      description: 'Retrieves information about an asynchronous job of permanently deleting all billing document PDF files for specific accounts.


        **Note**: This operation can be used only if you have the Billing user permission "Hard Delete Billing Document Files" enabled.'
      tags:
      - Billing Documents
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: jobId
        in: path
        description: The unique ID of a billing document file deletion job. For example, 2c92c8f83dc4f752013dc72c24ee016c.
        required: true
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GETBillingDocumentFilesDeletionJobResponse'
              example:
                id: 2c92c8f83dc4f752013dc72c24ee016c
                status: Pending
                success: true
components:
  schemas:
    BillingDocumentQueryResponseElementType:
      properties:
        documents:
          description: 'Container for billing documents.

            '
          items:
            $ref: '#/components/schemas/GETBillingDocumentsResponseType'
          type: array
        nextPage:
          description: 'URL to retrieve the next page of the response if it exists; otherwise absent.

            '
          format: URL
          type: string
        success:
          description: Returns `true` if the request was processed successfully.
          type: boolean
      type: object
    CreditMemoResponseType:
      properties:
        id:
          description: 'The ID of the generated credit memo.

            '
          type: string
      title: creditMemos
      type: object
    GETBillingDocumentFilesDeletionJobResponse:
      properties:
        id:
          description: 'The unique ID of the billing document file deletion job.

            '
          type: string
        status:
          description: 'The status of the billing document file deletion job.

            '
          enum:
          - Pending
          - Processing
          - Completed
          - Error
          type: string
        success:
          description: Returns `true` if the request was processed successfully.
          type: boolean
      type: object
    POSTBillingDocumentFilesDeletionJobResponse:
      properties:
        id:
          description: 'The unique ID of the billing document file deletion job.

            '
          type: string
        status:
          description: 'The status of the billing document file deletion job.

            '
          enum:
          - Pending
          type: string
        success:
          description: Returns `true` if the request was processed successfully.
          type: boolean
      type: object
    GETBillingDocumentsResponseType:
      properties:
        accountId:
          description: The ID of the customer account associated with the billing document.
          format: uuid
          type: string
        amount:
          description: 'The total amount of the billing document.

            '
          format: double
          type: number
        balance:
          description: 'The balance of the billing document.

            '
          format: double
          type: number
        documentDate:
          description: 'The date of the billing document. The date can be the invoice date for invoices, credit memo date for credit memos, or debit memo date for debit memos.

            '
          format: date
          type: string
        documentNumber:
          description: 'The number of the billing document.

            '
          type: string
        documentType:
          description: 'The type of the billing document.

            '
          enum:
          - Invoice
          - CreditMemo
          - DebitMemo
          type: string
        id:
          description: 'The ID of the billing document.

            '
          type: string
        status:
          description: 'The current status of the billing document.

            '
          enum:
          - Draft
          - Posted
          - Canceled
          - Error
          type: string
      title: documents
      type: object
    InvoiceResponseType:
      properties:
        id:
          description: 'The ID of the generated invoice.

            '
          type: string
      title: invoices
      type: object
    PostGenerateBillingDocumentType:
      example:
        autoPost: false
        creditMemoReasonCode: Unsatisfactory service
        effectiveDate: '2017-05-23'
        subscriptionIds:
        - 4028905558b483220158b48983dd0015
        - 6028905558b483220158b68983dd0016
        targetDate: '2017-08-23'
      properties:
        autoPost:
          default: false
          description: "Whether to automatically post the billing documents after the draft billing documents are generated. \n\nIf an error occurs during posting billing documents, the draft billing documents are not generated too.\n"
          enum:
          - true
          - false
          type: boolean
        autoRenew:
          default: false
          description: "Whether to automatically renew the subscriptions with **Auto Renew** set to **Yes**. \n"
          enum:
          - true
          - false
          type: boolean
        chargeTypeToExclude:
          description: "The types of the charges to be excluded from the generation of billing documents. The field values are case insensitive. Supported values include `onetime`, `recurring`, and `usage`. \n"
          items:
            type: string
          type: array
        creditMemoReasonCode:
          description: A code identifying the reason for the credit memo transaction that is generated by the request. The value must be an existing reason code. If you do not pass the field or pass the field with empty value, Zuora uses the default reason code.
          type: string
        effectiveDate:
          description: 'The date on which to generate the billing documents, in `yyyy-mm-dd` format.

            '
          format: date
          type: string
        subscriptionIds:
          description: 'The IDs of the subscriptions that you want to create the billing documents for. Each value must be the ID of the latest version of an active subscription.

            '
          items:
            type: string
          type: array
        targetDate:
          description: 'The date used to determine which charges are to be billed, in `yyyy-mm-dd` format.

            '
          format: date
          type: string
      type: object
    GenerateBillingDocumentResponseType:
      properties:
        creditMemos:
          description: 'Container for generated credit memos.


            **Note:** This container is only available if you have [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement) enabled. The Invoice Settlement feature is generally available as of Zuora Billing Release 296 (March 2021). This feature includes Unapplied Payments, Credit and Debit Memo, and Invoice Item Settlement. If you want to enable Invoice Settlement, see [Invoice Settlement Enablement and Checklist Guide](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement/Invoice_Settlement_Migration_Checklist_and_Guide) for more information.

            '
          items:
            $ref: '#/components/schemas/CreditMemoResponseType'
          type: array
        invoices:
          description: 'Container for generated invoics.

            '
          items:
            $ref: '#/components/schemas/InvoiceResponseType'
          type: array
        success:
          description: Returns `true` if the request was processed successfully.
          type: boolean
      type: object
    POSTBillingDocumentFilesDeletionJobRequest:
      example:
        accountIds:
        - 4028905558b483220158b48983dd0015
        - 6028905558b483220158b68983dd0016
        accountKeys:
        - 4028905558b483220158b48983dd0015
        - A00000001
      properties:
        accountIds:
          description: 'Container for the IDs of the accounts that you want to create the billing document files deletion job for.


            **Note**: When creating jobs to delete billing document PDF files, you must specify either set of `accountIds` or `accountKeys` in the request body.

            '
          items:
            type: string
          type: array
        accountKeys:
          description: 'Container for the IDs and/or numbers of the accounts that you want to create the billing document files deletion job for.


            **Note**: When creating jobs to delete billing document PDF files, you must specify either set of `accountIds` or `accountKeys` in the request body.

            '
          items:
            type: string
          type: array
      type: object
  parameters:
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Authorization_OAuth_optional:
      name: Authorization
      in: header
      required: false
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_REQUEST_pageSize:
      name: pageSize
      in: query
      required: false
      description: 'The number of records returned per page in the response.

        '
      schema:
        type: integer
        default: 20
        maximum: 40
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_REQUEST_page:
      name: page
      in: query
      required: false
      description: 'The index number of the page that you want to retrieve. This parameter is dependent on `pageSize`. You must set `pageSize` before specifying `page`. For example, if you set `pageSize` to `20` and `page` to `2`, the 21st to 40th records are returned in the response.

        '
      schema:
        type: integer
        default: 1
        minimum: 1
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
