openapi: 3.2.0
info:
  version: '2023-12-15'
  title: Reference Payment Authorization API
  description: '# Introduction


    Welcome to the REST API reference for the Zuora Billing, Payments, and Central Platform!'
  contact:
    email: docs@zuora.com
servers:
- url: https://rest.zuora.com/
tags:
- name: Payment Authorization
  description: 'The Delayed Capture feature allows you to authorize the availability of funds for a transaction but delay the capture of funds until a later time.


    You can use the Create authorization operation to authorize a payment amount before capturing the payment.

    Subsequently, you can use Create a payment or Create an order to capture the authorized funds, or use Cancel authorization to cancel the authorization.'
paths:
  /v1/payment-methods/{payment-method-id}/authorize:
    post:
      description: 'Enables you to authorize the availability of funds for a transaction but delay the capture of funds until a later time. Subsequently, use Create a payment or Create an order to capture the authorized funds, or use Cancel authorization to cancel the authorization.


        For gateway integrations that support this operation, see Delayed Capture.'
      summary: Create authorization
      operationId: POST_CreateAuthorization
      tags:
      - Payment Authorization
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: payment-method-id
        in: path
        description: 'The unique ID of the payment method where the authorization is created.

          '
        required: true
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/POSTAuthorizeResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTDelayAuthorizeCapture'
        required: true
  /v1/payment-methods/{payment-method-id}/voidAuthorize:
    post:
      description: Allows you to cancel an authorization. For gateway integrations that support this operation, see Delayed Capture.
      summary: Cancel authorization
      operationId: POST_CancelAuthorization
      tags:
      - Payment Authorization
      parameters:
      - $ref: '#/components/parameters/GLOBAL_HEADER_Idempotency_Key'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Accept_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Content_Encoding'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Authorization_OAuth_optional'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Track_Id'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Entity_Ids_Single'
      - $ref: '#/components/parameters/GLOBAL_HEADER_Zuora_Org_Ids'
      - name: payment-method-id
        in: path
        description: 'The unique ID of the payment method where the authorization is cancelled.

          '
        required: true
        schema:
          type: string
      responses:
        '200':
          headers:
            Content-Encoding:
              description: "This header is returned if you specify the `Accept-Encoding: gzip` request header and the response contains over 1000 bytes of data.\n\nNote that only the following MIME types support gzipped responses:\n  - `application/json`\n  - `application/xml`\n  - `text/html`\n  - `text/csv`\n  - `text/plain`\n"
              schema:
                type: string
            RateLimit-Limit:
              description: 'The request limit quota for the time window closest to exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: string
            RateLimit-Remaining:
              description: 'The number of requests remaining in the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            RateLimit-Reset:
              description: 'The number of seconds until the quota resets for the time window closest to quota exhaustion. See [rate limits](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Policies/Concurrent_Request_Limits#Rate_limits) for more information.

                '
              schema:
                type: number
            Zuora-Request-Id:
              description: 'The Zuora internal identifier of the API call. You cannot control the value of this header.

                '
              schema:
                type: string
                maxLength: 36
                minLength: 36
            Zuora-Track-Id:
              description: 'A custom identifier for tracing the API call. If you specified a tracing identifier in the request headers, Zuora returns the same tracing identifier. Otherwise, Zuora does not set this header.

                '
              schema:
                type: string
                maxLength: 64
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/POSTVoidAuthorizeResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/POSTVoidAuthorize'
        required: true
components:
  parameters:
    GLOBAL_HEADER_Idempotency_Key:
      name: Idempotency-Key
      in: header
      required: false
      description: "Specify a unique idempotency key if you want to perform an idempotent POST or PATCH request. Do not use this header in other request types. \n\nWith this header specified, the Zuora server can identify subsequent retries of the same request using this value, which prevents the same operation from being performed multiple times by accident. \n"
      schema:
        type: string
        maxLength: 255
    GLOBAL_HEADER_Accept_Encoding:
      name: Accept-Encoding
      in: header
      required: false
      description: "Include the `Accept-Encoding: gzip` header to compress responses as a gzipped file. It can significantly reduce the bandwidth required for a response. \n\nIf specified, Zuora automatically compresses responses that contain over 1000 bytes of data, and the response contains a `Content-Encoding` header with the compression algorithm so that your client can decompress it.\n"
      schema:
        type: string
    GLOBAL_HEADER_Content_Encoding:
      name: Content-Encoding
      in: header
      required: false
      description: 'Include the `Content-Encoding: gzip` header to compress a request. With this header specified, you should upload a gzipped file for the request payload instead of sending the JSON payload.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Track_Id:
      name: Zuora-Track-Id
      in: header
      required: false
      description: 'A custom identifier for tracing the API call. If you set a value for this header, Zuora returns the same value in the response headers. This header enables you to associate your system process identifiers with Zuora API calls, to assist with troubleshooting in the event of an issue.


        The value of this field must use the US-ASCII character set and must not include any of the following characters: colon (`:`), semicolon (`;`), double quote (`"`), and quote (`''`).

        '
      schema:
        type: string
        maxLength: 64
    GLOBAL_HEADER_Authorization_OAuth_optional:
      name: Authorization
      in: header
      required: false
      description: 'The value is in the `Bearer {token}` format where {token} is a valid OAuth token generated by calling [Create an OAuth token](/api-references/api/operation/createToken).

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Entity_Ids_Single:
      name: Zuora-Entity-Ids
      in: header
      required: false
      description: 'An entity ID. If you have [Zuora Multi-entity](https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity) enabled and the OAuth token is valid for more than one entity, you must use this header to specify which entity to perform the operation in. If the OAuth token is only valid for a single entity, or you do not have Zuora Multi-entity enabled, you do not need to set this header.

        '
      schema:
        type: string
    GLOBAL_HEADER_Zuora_Org_Ids:
      name: Zuora-Org-Ids
      in: header
      required: false
      description: "Comma separated IDs. If you have <a href=\"https://knowledgecenter.zuora.com/Zuora_Central_Platform/Multi-Org\" target=\"_blank\">Zuora Multi-Org</a> enabled, \nyou can use this header to specify which orgs to perform the operation in. If you do not have Zuora Multi-Org enabled, you should not set this header.\n\nThe IDs must be a sub-set of the user's accessible orgs. If you specify an org that the user does not have access to, the operation fails.\n\nIf the header is not set, the operation is performed in scope of the user's accessible orgs.\n"
      schema:
        type: string
  schemas:
    POSTVoidAuthorize:
      example:
        accountId: 402881e861bd8a7e0161c6a453750026
        accountNumber: A00000004
        gatewayOrderId: A001
        transactionId: '5205213224866613203009'
      properties:
        accountId:
          description: The ID of the customer account. This field is generally required, but is optional if you are using the Ingenico ePayments gateway.
          type: string
        accountNumber:
          description: The number of the customer account. This field is generally required, but is optional if you are using the Ingenico ePayments gateway.
          type: string
        gatewayOptions:
          description: 'The field used to pass gateway-specific parameters and parameter values. The fields supported by gateways vary. For more information, see the Overview topic of each gateway integration in [Zuora Knowledge Center](https://knowledgecenter.zuora.com/Zuora_Billing/Billing_and_Payments/M_Payment_Gateways/Supported_Payment_Gateways).


            Zuora sends all the information that you specified to the gateway. If you specify any unsupported gateway option parameters, they will be ignored without error prompts.

            '
          properties:
            key:
              description: 'The name of a gateway-specific parameter.

                '
              type: string
            value:
              description: 'The value of the gateway-specific parameter.

                '
              type: string
          type: object
        gatewayOrderId:
          description: 'The order ID for the specific gateway.


            The specified order ID will be used in transaction authorization. If you specify an empty value for this field, Zuora will generate an ID and you will have to associate this ID with your order ID by yourself if needed. It is recommended to specify an ID for this field.

            '
          type: string
        paymentGatewayId:
          description: The ID of the payment gateway instance. This field is required if you do not specify the `accountId` and `accountNumber` fields.
          type: string
        transactionId:
          description: The ID of the transaction.
          type: string
      required:
      - transactionId
      - gatewayOrderId
      type: object
    POSTVoidAuthorizeResponse:
      example:
        gatewayOrderId: A001
        resultCode: 0
        resultMessage: 'Request ID: 5231719060426316203012'
        success: true
        transactionId: '5231719060426316203012'
      properties:
        gatewayOrderId:
          description: 'The order ID for the specific gateway.


            The specified order ID will be used in transaction authorization. If you specify an empty value for this field, Zuora will generate an ID and you will have to associate this ID with your order ID by yourself if needed. It is recommended to specify an ID for this field.

            '
          type: string
        resultCode:
          description: "The result code of the request. \n\n0 indicates that the request succeeded, and the following values indicate that the request failed:\n  - 1: The request is declined.\n  - 7: The field format is not correct.\n  - 10: Client connection has timed out.\n  - 11: Host connection has timed out.\n  - 12: Processor connection has timed out.\n  - 13: Gateway server is busy.\n  - 20: The card type is not supported.\n  - 21: The merchant account information is invalid.\n  - 22: A generic error occurred on the processor.\n  - 40: The card type has not been set up yet.\n  - 41: The limit for a single transaction is exceeded.\n  - 42: Address checking failed.\n  - 43: Card security code checking failed.\n  - 44: Failed due to the gateway security setting.\n  - 45: Fraud protection is declined.\n  - 46: Address checking or card security code checking failed (for Authorize.net gateway only).\n  - 47: The maximum amount is exceeded (for Authorize.net gateway only).\n  - 48: The IP address is blocked by the gateway (for Authorize.net gateway only).\n  - 49: Card security code checking failed (for Authorize.net gateway only).\n  - 60: User authentication failed.\n  - 61: The currency code is invalid.\n  - 62: The transaction ID is invalid.\n  - 63: The credit card number is invalid.\n  - 64: The card expiration date is invalid.\n  - 65: The transaction is duplicated.\n  - 66: Credit transaction error.\n  - 67: Void transaction error.\n  - 90: A valid amount is required.\n  - 91: The BA code is invalid.\n  - 92: The account number is invalid.\n  - 93: The ACH transaction is not accepted by the merchant.\n  - 94: An error occurred for the ACH transaction.\n  - 95: The version parameter is invalid.\n  - 96: The transaction type is invalid.\n  - 97: The transaction method is invalid.\n  - 98: The bank account type is invalid.\n  - 99: The authorization code is invalid.\n  - 200: General transaction error.\n  - 500: The transaction is queued for submission.\n  - 999: Unknown error.\n  - -1: An error occurred in gateway communication.\n  - -2: Idempotency is not supported.\n  - -3: Inquiry call is not supported.\n"
          type: string
        resultMessage:
          description: The corresponding request ID.
          type: string
        success:
          description: Indicates whether the call succeeded.
          type: boolean
        transactionId:
          description: The ID of the transaction.
          type: string
      type: object
    POSTDelayAuthorizeCapture:
      example:
        accountId: 402881e861bd8a7e0161c6a453750026
        accountNumber: A00000004
        amount: 1.99
        gatewayOrderId: A001
        softDescriptor: Service fee
        softDescriptorPhone: 400-000-1234
      properties:
        accountId:
          description: The ID of the customer account. Either `accountId` or `accountNumber` is required.
          type: string
        accountNumber:
          description: The number of the customer account. Either `accountNumber` or `accountId` is required.
          type: string
        amount:
          description: The amount of the trasaction.
          type: number
        gatewayOptions:
          description: 'The field used to pass gateway-specific parameters and parameter values. The fields supported by gateways vary. For more information, see the Overview topic of each gateway integration in [Zuora Knowledge Center](https://knowledgecenter.zuora.com/Zuora_Billing/Billing_and_Payments/M_Payment_Gateways/Supported_Payment_Gateways).


            Zuora sends all the information that you specified to the gateway. If you specify any unsupported gateway option parameters, they will be ignored without error prompts.

            '
          properties:
            key:
              description: 'The name of a gateway-specific parameter.

                '
              type: string
            value:
              description: 'The value of the gateway-specific parameter.

                '
              type: string
          type: object
        gatewayOrderId:
          description: 'The order ID for the specific gateway.


            The specified order ID will be used in transaction authorization. If you specify an empty value for this field, Zuora will generate an ID and you will have to associate this ID with your order ID by yourself if needed. It is recommended to specify an ID for this field.

            '
          type: string
        mitTransactionSource:
          description: "Payment transaction source used to differentiate the transaction source in Stored Credential Transaction framework.\n  - `C_Unscheduled`: Cardholder-initiated transaction (CIT) that does not occur on scheduled or regularly occurring dates.\n  - `M_Recurring`: Merchant-initiated transaction (MIT) that occurs at regular intervals.\n  - `M_Unscheduled`: Merchant-initiated transaction (MIT) that does not occur on scheduled or regularly occurring dates.\n  - `M_MOTO`: Mail Order Telephone Order (MOTO) payment transaction. This option is only available for credit card payments on Stripe v2. See [Overview of Stripe payment gateway integration](https://knowledgecenter.zuora.com/Zuora_Collect/Payment_gateway_integrations/Supported_payment_gateways/Stripe_Payment_Gateway/A_Overview_of_Stripe_payment_gateway_integration) for more information.\n"
          enum:
          - C_Unscheduled
          - M_Recurring
          - M_Unscheduled
          - M_MOTO
          type: string
        paymentGatewayId:
          description: The ID of the payment gateway instance.
          type: string
        softDescriptor:
          description: A text, rendered on a cardholder’s statement, describing a particular product or service purchased by the cardholder.
          type: string
        softDescriptorPhone:
          description: The phone number that relates to the soft descriptor, usually the phone number of customer service.
          type: string
      required:
      - amount
      - gatewayOrderId
      type: object
    POSTAuthorizeResponse:
      example:
        gatewayOrderId: A001
        resultCode: 0
        resultMessage: 'Request ID: 5231719060426316203012'
        success: true
        transactionId: '5231719060426316203012'
      properties:
        gatewayOrderId:
          description: 'The order ID for the specific gateway.


            The specified order ID will be used in transaction authorization. If you specify an empty value for this field, Zuora will generate an ID and you will have to associate this ID with your order ID by yourself if needed. It is recommended to specify an ID for this field.

            '
          type: string
        paymentGatewayResponse:
          description: 'The response data returned from the gateway. This field is available only if the `success` field is `false` and the support for returning additional error information from the gateway is enabled.

            '
          properties:
            additionalInfo:
              description: "The additional information returned from the gateway. The returned fields vary for gateways. Here is an example.\n\n```\n\"additionalInfo\": {\n  \"ProcessorName\": \"MasterCard Saferpay Test\",\n  \"ProcessorResult\": \"51\",\n  \"ProcessorMessage\": \"Insufficient funds\",\n  \"ErrorName\": \"TRANSACTION_DECLINED\"\n}\n```\n"
              type: object
            gatewayResponseCode:
              description: 'The HTTP response code.

                '
              type: string
            gatewayResponseMessage:
              description: 'The error message returned from the gateway.

                '
              type: string
            gatewayType:
              description: 'The gateway type.

                '
              type: string
            gatewayVersion:
              description: 'The gateway version.

                '
              type: string
          type: object
        processId:
          description: 'The ID of the running process when the exception occurs. This field is available only if the `success` field is `false`.

            '
          type: string
        reasons:
          description: 'The container of the error code and message. This field is available only if the `success` field is `false`.

            '
          items:
            properties:
              code:
                description: 'Error code.

                  '
                type: string
              message:
                description: 'Error message. It usually contains a combination of gateway response code and response message.

                  '
                type: string
            type: object
          type: array
        requestId:
          description: 'The ID of the request. This field is available only if the `success` field is `false`

            '
          type: string
        resultCode:
          description: "The result code of the request. \n\n0 indicates that the request succeeded, and the following values indicate that the request failed:\n  - 1: The request is declined.\n  - 7: The field format is not correct.\n  - 10: Client connection has timed out.\n  - 11: Host connection has timed out.\n  - 12: Processor connection has timed out.\n  - 13: Gateway server is busy.\n  - 20: The card type is not supported.\n  - 21: The merchant account information is invalid.\n  - 22: A generic error occurred on the processor.\n  - 40: The card type has not been set up yet.\n  - 41: The limit for a single transaction is exceeded.\n  - 42: Address checking failed.\n  - 43: Card security code checking failed.\n  - 44: Failed due to the gateway security setting.\n  - 45: Fraud protection is declined.\n  - 46: Address checking or card security code checking failed (for Authorize.net gateway only).\n  - 47: The maximum amount is exceeded (for Authorize.net gateway only).\n  - 48: The IP address is blocked by the gateway (for Authorize.net gateway only).\n  - 49: Card security code checking failed (for Authorize.net gateway only).\n  - 60: User authentication failed.\n  - 61: The currency code is invalid.\n  - 62: The transaction ID is invalid.\n  - 63: The credit card number is invalid.\n  - 64: The card expiration date is invalid.\n  - 65: The transaction is duplicated.\n  - 66: Credit transaction error.\n  - 67: Void transaction error.\n  - 90: A valid amount is required.\n  - 91: The BA code is invalid.\n  - 92: The account number is invalid.\n  - 93: The ACH transaction is not accepted by the merchant.\n  - 94: An error occurred for the ACH transaction.\n  - 95: The version parameter is invalid.\n  - 96: The transaction type is invalid.\n  - 97: The transaction method is invalid.\n  - 98: The bank account type is invalid.\n  - 99: The authorization code is invalid.\n  - 200: General transaction error.\n  - 500: The transaction is queued for submission.\n  - 999: Unknown error.\n  - -1: An error occurred in gateway communication.\n  - -2: Idempotency is not supported.\n  - -3: Inquiry call is not supported.\n"
          type: string
        resultMessage:
          description: The corresponding request ID.
          type: string
        success:
          description: Indicates whether the call succeeded.
          type: boolean
        transactionId:
          description: The ID of the transaction.
          type: string
      type: object
x-tagGroups:
- name: Authentication
  tags:
  - OAuth
- name: Products
  tags:
  - Products
  - Catalog
  - Catalog Groups
  - Offers
  - Price Book Items
  - Product Rate Plans
  - Product Rate Plan Definitions
  - Product Rate Plan Charges
  - Product Charge Definitions
  - Product Rate Plan Charge Tiers
  - Zuora Revenue Integration
- name: Customer Accounts
  tags:
  - Accounts
  - Contacts
  - Contact Snapshots
- name: Orders and Subscriptions
  tags:
  - Sign Up
  - Orders
  - Order Actions
  - Order Line Items
  - Fulfillments
  - Ramps
  - Subscriptions
  - Rate Plans
- name: Advanced Consumption Billing
  tags:
  - Prepaid with Drawdown
- name: Usage
  tags:
  - Usage
- name: Billing Documents
  tags:
  - Delivery Adjustments
  - Billing Documents
  - Invoices
  - Credit Memos
  - Debit Memos
  - E-Invoicing
  - Invoice Schedules
  - Taxation Items
  - Sequence Sets
  - Operations
- name: Bill Runs
  tags:
  - Bill Run
  - Billing Preview Run
- name: Payment Methods
  tags:
  - Payment Methods
  - Custom Payment Method Types
  - Payment Method Updater
  - Payment Method Snapshots
  - Payment Method Transaction Logs
  - Hosted Pages
  - RSA Signatures
- name: Payments
  tags:
  - Payment Authorization
  - Payment Gateways
  - Payment Gateway Reconciliation
  - Payments
  - Payment Transaction Logs
  - Payment Runs
  - Payment Schedules
  - Refunds
- name: Finance
  tags:
  - Accounting Codes
  - Accounting Periods
  - Summary Journal Entries
  - Journal Runs
  - Mass Updater
- name: Events and Notifications
  tags:
  - Notifications
  - Custom Event Triggers
  - Custom Scheduled Events
- name: Custom Objects
  tags:
  - Custom Object Definitions
  - Custom Object Records
  - Custom Object Jobs
- name: System Health
  tags:
  - API Health
  - Bill Run Health
  - Electronic Payments Health
- name: Workflow
  tags:
  - Workflows
- name: Data Query
  tags:
  - Data Queries
- name: AQuA
  tags:
  - Aggregate Queries
- name: Deployment Manager
  tags:
  - Configuration Templates
- name: Multiple Organizations
  tags:
  - Data Labeling
- name: Order to Revenue
  tags:
  - Regenerate
- name: General-Purpose Operations
  tags:
  - Actions
  - Settings
  - Files
  - Imports
  - Custom Exchange Rates
  - Attachments
  - Describe
